# Generated by Django 5.2.17 on 2026-10-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("log_name", models.CharField(max_length=128, unique=True)),
                ("display_name", models.CharField(max_length=128)),
                (
                    "cls",
                    models.CharField(
                        choices=[
                            ("fighter", "Fighter"),
                            ("attacker", "Attacker"),
                            ("bomber", "Bomber"),
                            ("transport", "Transport"),
                            ("gunner", "Gunner"),
                            ("vehicle", "Vehicle"),
                            ("tank", "Tank"),
                            ("aaa", "Aaa"),
                            ("ship", "Ship"),
                            ("static", "Static"),
                            ("ordnance", "Ordnance"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("is_playable", models.BooleanField(default=False)),
                ("is_known", models.BooleanField(default=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "cls__in",
                                [
                                    "fighter",
                                    "attacker",
                                    "bomber",
                                    "transport",
                                    "gunner",
                                    "vehicle",
                                    "tank",
                                    "aaa",
                                    "ship",
                                    "static",
                                    "ordnance",
                                    "unknown",
                                ],
                            )
                        ),
                        name="gameobject_cls_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("log_name", ""), _negated=True), name="gameobject_log_name_not_empty"
                    ),
                ],
            },
        ),
    ]
