# Generated by Django 5.2.17 on 2026-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reprocessrequest",
            name="phase",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="reprocessrequest",
            name="wipe",
            field=models.BooleanField(default=False),
        ),
    ]
