# Generated by Django 5.2.17 on 2026-10-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="notice_level",
            field=models.CharField(
                choices=[("info", "Information"), ("warning", "Warning")], default="info", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notice_text",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notice_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
