# Generated by Django 5.2.17 on 2026-10-03 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.IntegerField(unique=True)),
                ("coalition", models.IntegerField()),
                ("display_name", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("account_uuid", models.CharField(max_length=36, unique=True)),
                ("current_name", models.CharField(max_length=128)),
                ("name_lower", models.CharField(db_index=True, max_length=128)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("is_hidden", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("server_uid", models.UUIDField()),
                ("mission_uid", models.CharField(max_length=32)),
                ("mission_file", models.CharField(max_length=255)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("duration_s", models.FloatField()),
                ("game_date", models.CharField(max_length=32)),
                ("game_time", models.CharField(max_length=32)),
                ("game_type", models.IntegerField()),
                ("settings", models.JSONField(default=dict)),
                ("countries", models.JSONField(default=dict)),
                ("log_version", models.IntegerField(null=True)),
                ("completed_cleanly", models.BooleanField()),
                ("winning_coalition", models.IntegerField(null=True)),
                ("is_hidden", models.BooleanField(default=False)),
                ("players_total", models.PositiveIntegerField(default=0)),
                ("sorties_total", models.PositiveIntegerField(default=0)),
                ("redfor_sorties", models.PositiveIntegerField(default=0)),
                ("blufor_sorties", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [models.Index(fields=["-started_at"], name="mission_started_desc")],
                "constraints": [
                    models.UniqueConstraint(fields=("server_uid", "mission_uid"), name="mission_natural_key")
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerSortie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_uuid", models.CharField(max_length=36)),
                ("spawn_tick", models.IntegerField()),
                ("name_at_time", models.CharField(max_length=128)),
                ("profile_uuid", models.CharField(max_length=36)),
                ("coalition", models.IntegerField()),
                ("country", models.IntegerField()),
                ("role", models.CharField(choices=[("pilot", "Pilot"), ("gunner", "Gunner")], max_length=8)),
                ("spawned_at", models.DateTimeField()),
                ("took_off_at", models.DateTimeField(null=True)),
                ("landed_at", models.DateTimeField(null=True)),
                ("ended_at", models.DateTimeField()),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("air_start", models.BooleanField(default=False)),
                (
                    "spawn_type",
                    models.CharField(
                        choices=[("air", "Air"), ("runway", "Runway"), ("parking", "Parking")], max_length=8
                    ),
                ),
                ("payload_id", models.IntegerField(default=0)),
                ("payload_name", models.CharField(blank=True, max_length=128)),
                ("weapon_mods", models.IntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("landed", "Landed"),
                            ("crashed", "Crashed"),
                            ("shot_down", "Shot Down"),
                            ("ditched", "Ditched"),
                            ("in_flight", "In Flight"),
                            ("not_taken_off", "Not Taken Off"),
                            ("mission_ended", "Mission Ended"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "pilot_fate",
                    models.CharField(
                        choices=[
                            ("in_aircraft", "In Aircraft"),
                            ("bailed_out", "Bailed Out"),
                            ("exited_on_ground", "Exited On Ground"),
                            ("mission_ended", "Mission Ended"),
                            ("disconnected", "Disconnected"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pilot_fate_source",
                    models.CharField(
                        choices=[("event", "Event"), ("inferred", "Inferred"), ("unknown", "Unknown")], max_length=10
                    ),
                ),
                (
                    "pilot_status",
                    models.CharField(
                        choices=[
                            ("healthy", "Healthy"),
                            ("wounded", "Wounded"),
                            ("dead", "Dead"),
                            ("captured", "Captured"),
                        ],
                        max_length=10,
                    ),
                ),
                ("suspected_early_bailout", models.BooleanField(default=False)),
                (
                    "aircraft_status",
                    models.CharField(
                        choices=[("unharmed", "Unharmed"), ("damaged", "Damaged"), ("destroyed", "Destroyed")],
                        max_length=10,
                    ),
                ),
                ("damage_taken", models.FloatField(default=0.0)),
                ("disconnected", models.BooleanField(default=False)),
                ("is_death", models.BooleanField(default=False)),
                ("is_plane_lost", models.BooleanField(default=False)),
                ("is_captured", models.BooleanField(default=False)),
                (
                    "loss_cause",
                    models.CharField(
                        choices=[("attacker", "Attacker"), ("self", "Self"), ("none", "None")], max_length=10
                    ),
                ),
                ("suspected_structural_failure", models.BooleanField(default=False)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("ammo", models.JSONField(default=dict)),
                ("damage_breakdown", models.JSONField(default=list)),
                ("timeline", models.JSONField(default=list)),
                ("pos_spawn_x", models.FloatField(null=True)),
                ("pos_spawn_y", models.FloatField(null=True)),
                ("pos_spawn_z", models.FloatField(null=True)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sortie_rows",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="sortie_rows", to="il2ks_db.mission"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="sortie_rows", to="il2ks_db.player"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kill",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("tick", models.IntegerField()),
                ("time", models.DateTimeField()),
                ("is_friendly", models.BooleanField(default=False)),
                (
                    "credit",
                    models.CharField(
                        choices=[("kill", "Kill"), ("assist", "Assist"), ("shared", "Shared")], max_length=8
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        choices=[
                            ("direct", "Direct"),
                            ("abandoned_aircraft", "Abandoned Aircraft"),
                            ("disconnect", "Disconnect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pos_x", models.FloatField(null=True)),
                ("pos_y", models.FloatField(null=True)),
                ("pos_z", models.FloatField(null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="kills", to="il2ks_db.mission"
                    ),
                ),
                (
                    "killer_sortie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kills_made",
                        to="il2ks_db.playersortie",
                    ),
                ),
                (
                    "victim_sortie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kills_suffered",
                        to="il2ks_db.playersortie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngestRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mission_uid", models.CharField(db_index=True, max_length=32)),
                ("files", models.JSONField(default=list)),
                ("fingerprint", models.CharField(max_length=64)),
                ("archive_path", models.CharField(blank=True, max_length=500)),
                ("archive_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[("ok", "Ok"), ("failed", "Failed"), ("skipped", "Skipped")], max_length=8
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=1)),
                ("next_retry_at", models.DateTimeField(null=True)),
                ("il2ks_version", models.CharField(blank=True, max_length=32)),
                ("started_at", models.DateTimeField()),
                ("finished_at", models.DateTimeField(null=True)),
                ("lines_total", models.PositiveIntegerField(default=0)),
                ("lines_bad", models.PositiveIntegerField(default=0)),
                ("log_version", models.IntegerField(null=True)),
                ("unknown_atypes", models.JSONField(default=dict)),
                ("unknown_keys", models.JSONField(default=dict)),
                ("warnings", models.JSONField(default=list)),
                ("error", models.TextField(blank=True)),
                (
                    "mission",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingest_runs",
                        to="il2ks_db.mission",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["mission_uid", "-started_at"], name="ingestrun_latest")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ok", "failed", "skipped"])), name="ingestrun_status_valid"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerAircraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_stats",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_stats", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("player", "aircraft"), name="playeraircraft_unique")],
            },
        ),
        migrations.CreateModel(
            name="PlayerMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("coalition", models.IntegerField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_missions",
                        to="il2ks_db.mission",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="missions", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("player", "mission"), name="playermission_unique")],
            },
        ),
        migrations.CreateModel(
            name="PlayerName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("name_lower", models.CharField(db_index=True, max_length=128)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="names", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("player", "name"), name="playername_unique")],
            },
        ),
        migrations.AddIndex(
            model_name="playersortie",
            index=models.Index(fields=["player", "-spawned_at"], name="sortie_player_recent"),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.UniqueConstraint(
                fields=("mission", "account_uuid", "spawn_tick"), name="sortie_natural_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("role__in", ["pilot", "gunner"])), name="sortie_role_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("spawn_type__in", ["air", "runway", "parking"])), name="sortie_spawn_type_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "landed",
                            "crashed",
                            "shot_down",
                            "ditched",
                            "in_flight",
                            "not_taken_off",
                            "mission_ended",
                            "unknown",
                        ],
                    )
                ),
                name="sortie_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "pilot_fate__in",
                        ["in_aircraft", "bailed_out", "exited_on_ground", "mission_ended", "disconnected", "unknown"],
                    )
                ),
                name="sortie_pilot_fate_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("pilot_fate_source__in", ["event", "inferred", "unknown"])),
                name="sortie_pilot_fate_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("pilot_status__in", ["healthy", "wounded", "dead", "captured"])),
                name="sortie_pilot_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("aircraft_status__in", ["unharmed", "damaged", "destroyed"])),
                name="sortie_aircraft_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("loss_cause__in", ["attacker", "self", "none"])), name="sortie_loss_cause_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("damage_taken__gte", 0), ("damage_taken__lte", 1)), name="sortie_damage_taken_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(("flight_time_s__gte", 0)), name="sortie_flight_time_nonneg"
            ),
        ),
        migrations.AddConstraint(
            model_name="kill",
            constraint=models.UniqueConstraint(
                fields=("killer_sortie", "victim_sortie", "tick", "credit"), name="kill_natural_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="kill",
            constraint=models.CheckConstraint(
                condition=models.Q(("credit__in", ["kill", "assist", "shared"])), name="kill_credit_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="kill",
            constraint=models.CheckConstraint(
                condition=models.Q(("via__in", ["direct", "abandoned_aircraft", "disconnect"])), name="kill_via_valid"
            ),
        ),
    ]
