# Generated by Django 5.2.17 on 2026-10-07 18:53

import django.db.models.deletion
from django.db import migrations, models

import il2ks.db.validators


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0002_reprocess_wipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("title", models.CharField(max_length=120)),
                ("base_language", models.CharField(default="en", max_length=10)),
                ("source", models.TextField(blank=True)),
                ("html", models.TextField(blank=True, editable=False)),
                ("translations", models.JSONField(blank=True, default=dict, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["title", "id"],
            },
        ),
        migrations.AlterField(
            model_name="navlink",
            name="url",
            field=models.CharField(blank=True, max_length=2000, validators=[il2ks.db.validators.validate_http_url]),
        ),
        migrations.AddField(
            model_name="navlink",
            name="page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nav_links",
                to="il2ks_db.page",
            ),
        ),
        migrations.CreateModel(
            name="PageTranslation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("language", models.CharField(max_length=10)),
                ("title", models.CharField(blank=True, max_length=120)),
                ("source", models.TextField(blank=True)),
                ("html", models.TextField(blank=True, editable=False)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_translations",
                        to="il2ks_db.page",
                    ),
                ),
            ],
            options={
                "ordering": ["language"],
                "constraints": [
                    models.UniqueConstraint(fields=("page", "language"), name="il2ks_pagetranslation_unique")
                ],
            },
        ),
    ]
