# Generated by Django 5.2.17 on 2026-10-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0002_level1_level2_ingest"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="gameobject",
            name="gameobject_cls_valid",
        ),
        migrations.RemoveConstraint(
            model_name="kill",
            name="kill_natural_key",
        ),
        migrations.AddField(
            model_name="ingestrun",
            name="completion_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("mission_end", "Mission End"),
                    ("newer_mission", "Newer Mission"),
                    ("idle", "Idle"),
                    ("import", "Import"),
                    ("reprocess", "Reprocess"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="mission",
            name="friendly_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="friendly_damage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="player",
            name="friendly_hits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="friendly_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="friendly_damage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="friendly_hits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="friendly_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="friendly_damage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="friendly_hits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="friendly_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="friendly_damage",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="friendly_hits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="friendly_kills",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="gameobject",
            name="cls",
            field=models.CharField(
                choices=[
                    ("fighter", "Fighter"),
                    ("attacker", "Attacker"),
                    ("bomber", "Bomber"),
                    ("transport", "Transport"),
                    ("gunner", "Gunner"),
                    ("vehicle", "Vehicle"),
                    ("tank", "Tank"),
                    ("aaa", "Aaa"),
                    ("ship", "Ship"),
                    ("static", "Static"),
                    ("ordnance", "Ordnance"),
                    ("crew", "Crew"),
                    ("equipment", "Equipment"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="gameobject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "cls__in",
                        [
                            "fighter",
                            "attacker",
                            "bomber",
                            "transport",
                            "gunner",
                            "vehicle",
                            "tank",
                            "aaa",
                            "ship",
                            "static",
                            "ordnance",
                            "crew",
                            "equipment",
                            "unknown",
                        ],
                    )
                ),
                name="gameobject_cls_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ingestrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("completion_reason__in", ["", "mission_end", "newer_mission", "idle", "import", "reprocess"])
                ),
                name="ingestrun_completion_reason_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="kill",
            constraint=models.UniqueConstraint(fields=("victim_sortie", "killer_sortie"), name="kill_natural_key"),
        ),
    ]
