# Generated by Django 5.2.17 on 2026-10-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0003_friendly_fire_crew_completion"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersortie",
            name="resupplied",
            field=models.BooleanField(default=False),
        ),
    ]
