# Generated by Django 5.2.17 on 2026-10-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0004_sortie_resupplied"),
    ]

    operations = [
        migrations.AddField(
            model_name="gameobject",
            name="propulsion",
            field=models.CharField(blank=True, choices=[("prop", "Prop"), ("jet", "Jet")], default="", max_length=4),
        ),
        migrations.AddField(
            model_name="player",
            name="attack_sorties",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="elo_jet",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="player",
            name="elo_jet_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="elo_prop",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="player",
            name="elo_prop_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="strafed_on_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="taxi_accidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="time_on_target_s",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="attack_sorties",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="strafed_on_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="taxi_accidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="time_on_target_s",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="attack_sorties",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="strafed_on_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="taxi_accidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="time_on_target_s",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="combat_role",
            field=models.CharField(
                choices=[("air_superiority", "Air Superiority"), ("attack", "Attack")], max_length=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="strafed_on_ground",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="taxi_accident",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="time_on_target_s",
            field=models.FloatField(null=True),
        ),
        migrations.AddConstraint(
            model_name="gameobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("propulsion__in", ["prop", "jet", ""])), name="gameobject_propulsion_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("combat_role__isnull", True), ("combat_role__in", ["air_superiority", "attack"]), _connector="OR"
                ),
                name="sortie_combat_role_valid",
            ),
        ),
    ]
