# Generated by Django 5.2.17 on 2026-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0004_side_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="renderer_version",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="pagetranslation",
            name="renderer_version",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
