# Generated by Django 5.2.17 on 2026-10-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0005_ground_losses_combat_role_elo"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("site_title", models.CharField(default="IL-2 Korea stats", max_length=100)),
                ("server_name", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("logo", models.CharField(blank=True, max_length=200)),
                ("accent_color", models.CharField(blank=True, max_length=7)),
                ("links", models.JSONField(blank=True, default=list)),
                ("redfor_name", models.CharField(default="REDFOR", max_length=40)),
                ("blufor_name", models.CharField(default="BLUFOR", max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
            },
        ),
    ]
