# Generated by Django 5.2.17 on 2026-10-03 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0006_site_settings_data_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "countries"},
        ),
    ]
