# Generated by Django 5.2.17 on 2026-10-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0007_country_plural_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="blufor_emblem",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("usaf", "US star-and-bar"),
                    ("rokaf", "South Korean ROKAF"),
                    ("un", "UN-style roundel"),
                ],
                default="neutral",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="redfor_emblem",
            field=models.CharField(
                choices=[
                    ("neutral", "Neutral"),
                    ("vvs", "Soviet VVS"),
                    ("plaaf", "Chinese PLAAF"),
                    ("kpaf", "North Korean KPAF"),
                ],
                default="neutral",
                max_length=10,
            ),
        ),
    ]
