# Generated by Django 5.2.17 on 2026-10-03 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0009_ground_kill_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=100)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(null=True)),
                ("mode", models.CharField(max_length=16)),
            ],
            options={
                "ordering": ["-started_at"],
                "constraints": [
                    models.UniqueConstraint(fields=("started_at",), name="tour_started_at_unique"),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("ended_at__isnull", True), ("ended_at__gt", models.F("started_at")), _connector="OR"
                        ),
                        name="tour_ends_after_start",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="mission",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="missions", to="il2ks_db.tour"
            ),
        ),
        migrations.CreateModel(
            name="PlayerTourAircraft",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("friendly_kills", models.PositiveIntegerField(default=0)),
                ("friendly_hits", models.PositiveIntegerField(default=0)),
                ("friendly_damage", models.FloatField(default=0.0)),
                ("taxi_accidents", models.PositiveIntegerField(default=0)),
                ("strafed_on_ground", models.PositiveIntegerField(default=0)),
                ("attack_sorties", models.PositiveIntegerField(default=0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("kills_ground_tank", models.PositiveIntegerField(default=0)),
                ("kills_ground_vehicle", models.PositiveIntegerField(default=0)),
                ("kills_ground_artillery", models.PositiveIntegerField(default=0)),
                ("kills_ground_aaa", models.PositiveIntegerField(default=0)),
                ("kills_ground_ship", models.PositiveIntegerField(default=0)),
                ("kills_ground_train", models.PositiveIntegerField(default=0)),
                ("kills_ground_building", models.PositiveIntegerField(default=0)),
                ("kills_ground_parked_aircraft", models.PositiveIntegerField(default=0)),
                ("kills_ground_other", models.PositiveIntegerField(default=0)),
                ("kills_ground_static", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tour_player_stats",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_aircraft_stats",
                        to="il2ks_db.player",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_rows", to="il2ks_db.tour"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(fields=("player", "tour", "aircraft"), name="playertouraircraft_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerTour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("friendly_kills", models.PositiveIntegerField(default=0)),
                ("friendly_hits", models.PositiveIntegerField(default=0)),
                ("friendly_damage", models.FloatField(default=0.0)),
                ("taxi_accidents", models.PositiveIntegerField(default=0)),
                ("strafed_on_ground", models.PositiveIntegerField(default=0)),
                ("attack_sorties", models.PositiveIntegerField(default=0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("kills_ground_tank", models.PositiveIntegerField(default=0)),
                ("kills_ground_vehicle", models.PositiveIntegerField(default=0)),
                ("kills_ground_artillery", models.PositiveIntegerField(default=0)),
                ("kills_ground_aaa", models.PositiveIntegerField(default=0)),
                ("kills_ground_ship", models.PositiveIntegerField(default=0)),
                ("kills_ground_train", models.PositiveIntegerField(default=0)),
                ("kills_ground_building", models.PositiveIntegerField(default=0)),
                ("kills_ground_parked_aircraft", models.PositiveIntegerField(default=0)),
                ("kills_ground_other", models.PositiveIntegerField(default=0)),
                ("kills_ground_static", models.PositiveIntegerField(default=0)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tour_rows", to="il2ks_db.player"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="player_rows", to="il2ks_db.tour"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("player", "tour"), name="playertour_unique")],
            },
        ),
    ]
