# Generated by Django 5.2.17 on 2026-10-03 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0009_ground_kill_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftAmmoStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ammo", models.CharField(max_length=128)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="ammo_stats", to="il2ks_db.gameobject"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("aircraft", "ammo"), name="aircraftammostats_unique")],
            },
        ),
        migrations.CreateModel(
            name="MissionAircraftAmmo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ammo", models.CharField(max_length=128)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_ammo",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_ammo", to="il2ks_db.mission"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("mission", "aircraft", "ammo"), name="missionaircraftammo_unique")
                ],
            },
        ),
    ]
