# Generated by Django 5.2.17 on 2026-10-03 16:55
# Split in three (data and constraint changes on one table cannot share a Postgres transaction):
# this schema part, then 0011_sortie_mission_end_data, then 0011_sortie_mission_end_constraints.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0010_pve_breakdown"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playersortie",
            name="sortie_outcome_valid",
        ),
        migrations.RemoveConstraint(
            model_name="playersortie",
            name="sortie_pilot_fate_valid",
        ),
        migrations.AddField(
            model_name="playersortie",
            name="ended_by_mission_end",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ReprocessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_at", models.DateTimeField()),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("since", models.DateField(null=True)),
                ("until", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("missions_total", models.PositiveIntegerField(default=0)),
                ("missions_ok", models.PositiveIntegerField(default=0)),
                ("missions_failed", models.PositiveIntegerField(default=0)),
                ("missions_missing", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-requested_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "running", "done", "failed"])),
                        name="reprocessrequest_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("status",),
                        name="reprocessrequest_one_pending",
                    ),
                ],
            },
        ),
    ]
