# Generated by Django 5.2.17 on 2026-10-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0011_sortie_mission_end_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playersortie",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("landed", "Landed"),
                    ("crashed", "Crashed"),
                    ("shot_down", "Shot Down"),
                    ("ditched", "Ditched"),
                    ("in_flight", "In Flight"),
                    ("airborne", "Airborne"),
                    ("not_taken_off", "Not Taken Off"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="playersortie",
            name="pilot_fate",
            field=models.CharField(
                choices=[
                    ("in_aircraft", "In Aircraft"),
                    ("bailed_out", "Bailed Out"),
                    ("exited_on_ground", "Exited On Ground"),
                    ("disconnected", "Disconnected"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "landed",
                            "crashed",
                            "shot_down",
                            "ditched",
                            "in_flight",
                            "airborne",
                            "not_taken_off",
                            "unknown",
                        ],
                    )
                ),
                name="sortie_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pilot_fate__in", ["in_aircraft", "bailed_out", "exited_on_ground", "disconnected", "unknown"])
                ),
                name="sortie_pilot_fate_valid",
            ),
        ),
    ]
