# Generated by Django 5.2.17 on 2026-10-03 16:55

from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
from django.db.models import F


def _retire_mission_ended(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Old rows: `mission_ended` fate/outcome become the new model (doc 13, sortie scope and mission end).

    - `ended_by_mission_end` = the old fate was `mission_ended` (it was set exactly when the sortie was forced).
    - fate `mission_ended` -> `in_aircraft` (same source): the pilot was still in the aircraft.
    - outcome `mission_ended` -> `airborne` when the counts show the aircraft was in the air (air start or takeoffs
      exceed landings); otherwise `unknown`: landed vs ditched needs the landing position, which isn't stored. Run
      `il2ks reprocess` to get the exact value for those.
    """
    sortie = apps.get_model("il2ks_db", "PlayerSortie")
    sortie.objects.filter(pilot_fate="mission_ended").update(ended_by_mission_end=True, pilot_fate="in_aircraft")
    forced = sortie.objects.filter(outcome="mission_ended")
    forced.filter(air_start=True, takeoffs__gte=F("landings")).update(outcome="airborne")
    forced.filter(air_start=False, takeoffs__gt=F("landings")).update(outcome="airborne")
    forced.update(outcome="unknown")


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0010_pve_breakdown"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playersortie",
            name="sortie_outcome_valid",
        ),
        migrations.RemoveConstraint(
            model_name="playersortie",
            name="sortie_pilot_fate_valid",
        ),
        migrations.AddField(
            model_name="playersortie",
            name="ended_by_mission_end",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(_retire_mission_ended, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="playersortie",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("landed", "Landed"),
                    ("crashed", "Crashed"),
                    ("shot_down", "Shot Down"),
                    ("ditched", "Ditched"),
                    ("in_flight", "In Flight"),
                    ("airborne", "Airborne"),
                    ("not_taken_off", "Not Taken Off"),
                    ("unknown", "Unknown"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="playersortie",
            name="pilot_fate",
            field=models.CharField(
                choices=[
                    ("in_aircraft", "In Aircraft"),
                    ("bailed_out", "Bailed Out"),
                    ("exited_on_ground", "Exited On Ground"),
                    ("disconnected", "Disconnected"),
                    ("unknown", "Unknown"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "outcome__in",
                        [
                            "landed",
                            "crashed",
                            "shot_down",
                            "ditched",
                            "in_flight",
                            "airborne",
                            "not_taken_off",
                            "unknown",
                        ],
                    )
                ),
                name="sortie_outcome_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playersortie",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("pilot_fate__in", ["in_aircraft", "bailed_out", "exited_on_ground", "disconnected", "unknown"])
                ),
                name="sortie_pilot_fate_valid",
            ),
        ),
        migrations.CreateModel(
            name="ReprocessRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("requested_at", models.DateTimeField()),
                ("requested_by", models.CharField(blank=True, max_length=150)),
                ("since", models.DateField(null=True)),
                ("until", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("missions_total", models.PositiveIntegerField(default=0)),
                ("missions_ok", models.PositiveIntegerField(default=0)),
                ("missions_failed", models.PositiveIntegerField(default=0)),
                ("missions_missing", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-requested_at", "-pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["pending", "running", "done", "failed"])),
                        name="reprocessrequest_status_valid",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("status",),
                        name="reprocessrequest_one_pending",
                    ),
                ],
            },
        ),
    ]
