# Generated by Django 5.2.17 on 2026-10-03 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0014_gameobject_name_overridden"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerKillboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kills", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("last_at", models.DateTimeField()),
                (
                    "last_mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.mission"
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.player"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="killboard_rows", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["player", "-kills"], name="killboard_by_kills"),
                    models.Index(fields=["player", "-deaths"], name="killboard_by_deaths"),
                ],
                "constraints": [models.UniqueConstraint(fields=("player", "opponent"), name="playerkillboard_unique")],
            },
        ),
        migrations.CreateModel(
            name="PlayerStreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_sorties", models.PositiveIntegerField(default=0)),
                ("current_kills_air", models.PositiveIntegerField(default=0)),
                ("current_flight_time_s", models.FloatField(default=0.0)),
                ("current_since", models.DateTimeField(null=True)),
                ("current_until", models.DateTimeField(null=True)),
                ("best_sorties", models.PositiveIntegerField(default=0)),
                ("best_kills_air", models.PositiveIntegerField(default=0)),
                ("best_flight_time_s", models.FloatField(default=0.0)),
                ("best_since", models.DateTimeField(null=True)),
                ("best_until", models.DateTimeField(null=True)),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="streak", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["-current_sorties"], name="streak_current_desc")],
            },
        ),
    ]
