# Generated by Django 5.2.17 on 2026-10-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0014_gameobject_name_overridden"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="player",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="player",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="air_points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="ground_points",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
    ]
