# Generated by Django 5.2.17 on 2026-10-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0014_gameobject_name_overridden"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityDay",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField(unique=True)),
                ("missions", models.PositiveIntegerField(default=0)),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("pilots", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
