# Generated by Django 5.2.17 on 2026-10-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0014_gameobject_name_overridden"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric", models.CharField(max_length=24)),
                ("min_sorties", models.PositiveIntegerField()),
                ("population", models.PositiveIntegerField()),
                ("p10", models.FloatField()),
                ("p25", models.FloatField()),
                ("p50", models.FloatField()),
                ("p75", models.FloatField()),
                ("p90", models.FloatField()),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stat_thresholds",
                        to="il2ks_db.tour",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", False)),
                        fields=("tour", "metric"),
                        name="statthreshold_tour_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", True)),
                        fields=("metric",),
                        name="statthreshold_alltime_unique",
                    ),
                ],
            },
        ),
    ]
