# Generated by Django 5.2.17 on 2026-10-03 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0015_ammo_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("friendly_kills", models.PositiveIntegerField(default=0)),
                ("friendly_hits", models.PositiveIntegerField(default=0)),
                ("friendly_damage", models.FloatField(default=0.0)),
                ("taxi_accidents", models.PositiveIntegerField(default=0)),
                ("strafed_on_ground", models.PositiveIntegerField(default=0)),
                ("attack_sorties", models.PositiveIntegerField(default=0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("kills_ground_tank", models.PositiveIntegerField(default=0)),
                ("kills_ground_vehicle", models.PositiveIntegerField(default=0)),
                ("kills_ground_artillery", models.PositiveIntegerField(default=0)),
                ("kills_ground_aaa", models.PositiveIntegerField(default=0)),
                ("kills_ground_ship", models.PositiveIntegerField(default=0)),
                ("kills_ground_train", models.PositiveIntegerField(default=0)),
                ("kills_ground_building", models.PositiveIntegerField(default=0)),
                ("kills_ground_parked_aircraft", models.PositiveIntegerField(default=0)),
                ("kills_ground_other", models.PositiveIntegerField(default=0)),
                ("kills_ground_static", models.PositiveIntegerField(default=0)),
                ("kills_air_pvp", models.PositiveIntegerField(default=0)),
                ("kills_air_ai", models.PositiveIntegerField(default=0)),
                ("deaths_by_player", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("deaths_by_aaa", models.PositiveIntegerField(default=0)),
                ("deaths_by_ground", models.PositiveIntegerField(default=0)),
                ("deaths_by_friendly", models.PositiveIntegerField(default=0)),
                ("deaths_by_environment", models.PositiveIntegerField(default=0)),
                ("deaths_by_unknown", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_player", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_aaa", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ground", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_friendly", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_environment", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_unknown", models.PositiveIntegerField(default=0)),
                ("pilots", models.PositiveIntegerField(default=0)),
                ("side", models.CharField(blank=True, default="", max_length=8)),
                ("kd", models.FloatField(default=0.0)),
                ("kl", models.FloatField(default=0.0)),
                ("survival", models.FloatField(default=0.0)),
                ("attack_share", models.FloatField(default=0.0)),
                (
                    "aircraft",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, related_name="stats", to="il2ks_db.gameobject"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AircraftMatchup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kills", models.PositiveIntegerField(default=0)),
                (
                    "killer_aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matchup_kills",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "victim_aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matchup_losses",
                        to="il2ks_db.gameobject",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("killer_aircraft", "victim_aircraft"), name="aircraftmatchup_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AircraftPayload",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("payload_name", models.CharField(blank=True, max_length=128)),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payload_stats",
                        to="il2ks_db.gameobject",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("aircraft", "payload_name"), name="aircraftpayload_unique")
                ],
            },
        ),
    ]
