# Generated by Django 5.2.17 on 2026-10-03 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0015_ammo_breakdown"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveMission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("server_uid", models.UUIDField(unique=True)),
                ("mission_uid", models.CharField(max_length=32)),
                ("mission_file", models.CharField(blank=True, max_length=255)),
                ("started_at", models.DateTimeField(null=True)),
                ("game_date", models.CharField(blank=True, max_length=32)),
                ("game_time", models.CharField(blank=True, max_length=32)),
                ("elapsed_s", models.FloatField(default=0.0)),
                ("updated_at", models.DateTimeField()),
                ("interval_s", models.FloatField(default=30.0)),
                ("is_running", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="LivePlayer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("account_uuid", models.CharField(max_length=36)),
                ("name", models.CharField(blank=True, max_length=128)),
                ("coalition", models.IntegerField(default=0)),
                ("country", models.IntegerField(default=0)),
                ("aircraft_type", models.CharField(blank=True, max_length=128)),
                ("aircraft_name", models.CharField(blank=True, max_length=128)),
                (
                    "propulsion",
                    models.CharField(blank=True, choices=[("prop", "Prop"), ("jet", "Jet")], default="", max_length=4),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("in_flight", "In Flight"),
                            ("on_ground", "On Ground"),
                            ("spawned", "Spawned"),
                            ("connected", "Connected"),
                        ],
                        max_length=10,
                    ),
                ),
                ("sortie_started_at", models.DateTimeField(null=True)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="players", to="il2ks_db.livemission"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="il2ks_db.player"
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("mission", "account_uuid"), name="liveplayer_unique")],
            },
        ),
    ]
