# Generated by Django 5.2.17 on 2026-10-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0019_killboard_streaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraftstats",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
