# Generated by Django 5.2.17 on 2026-10-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0019_killboard_streaks"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerkillboard",
            name="assists",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="killboard_assists",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PlayerBestStreak",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("sorties", "Sorties"), ("air_kills", "Air Kills"), ("flight_time", "Flight Time")],
                        max_length=12,
                    ),
                ),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("since", models.DateTimeField()),
                ("until", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="best_streaks", to="il2ks_db.player"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="best_streaks",
                        to="il2ks_db.tour",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["player", "tour"], name="bests_by_player_tour")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", False)),
                        fields=("player", "tour", "kind"),
                        name="bests_tour_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", True)),
                        fields=("player", "kind"),
                        name="bests_alltime_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["sorties", "air_kills", "flight_time"])),
                        name="bests_kind_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlayerTourKillboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kills", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("last_at", models.DateTimeField()),
                (
                    "last_mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.mission"
                    ),
                ),
                (
                    "opponent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.player"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tour_killboard_rows",
                        to="il2ks_db.player",
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="killboard_rows", to="il2ks_db.tour"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["player", "tour", "-kills"], name="tourkillboard_by_kills"),
                    models.Index(fields=["player", "tour", "-deaths"], name="tourkillboard_by_deaths"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("player", "tour", "opponent"), name="playertourkillboard_unique")
                ],
            },
        ),
    ]
