# Generated by Django 5.2.17 on 2026-10-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0021_sortie_and_player_scores"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraftstats",
            name="score_air",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aircraftstats",
            name="score_ground",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aircraftstats",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
    ]
