# Generated by Django 5.2.17 on 2026-10-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0025_player_aircraft_elo_and_pools"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerpool",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertourpool",
            name="friendly_fire_incidents",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
