# Generated by Django 5.2.17 on 2026-10-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0027_site_theme_nav_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="custom_fonts",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
