# Generated by Django 5.2.17 on 2026-10-04 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0027_site_theme_nav_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerTypeKillboard",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kills", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="aircraftmatchup",
            name="aircraftmatchup_unique",
        ),
        migrations.AddField(
            model_name="aircraftmatchup",
            name="intercept",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aircraftmatchup",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft_matchups",
                to="il2ks_db.tour",
            ),
        ),
        migrations.AddIndex(
            model_name="aircraftmatchup",
            index=models.Index(fields=["killer_aircraft", "tour", "intercept"], name="matchup_by_killer"),
        ),
        migrations.AddConstraint(
            model_name="aircraftmatchup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("killer_aircraft", "victim_aircraft", "tour", "intercept"),
                name="aircraftmatchup_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmatchup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("killer_aircraft", "victim_aircraft", "intercept"),
                name="aircraftmatchup_alltime_unique",
            ),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="deaths_in",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="il2ks_db.gameobject"
            ),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="enemy_aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="+", to="il2ks_db.gameobject"
            ),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="kills_with",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="il2ks_db.gameobject"
            ),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="type_killboard_rows", to="il2ks_db.player"
            ),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_killboard_rows",
                to="il2ks_db.tour",
            ),
        ),
        migrations.AddIndex(
            model_name="playertypekillboard",
            index=models.Index(fields=["player", "tour"], name="typekillboard_by_player"),
        ),
        migrations.AddConstraint(
            model_name="playertypekillboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("player", "tour", "enemy_aircraft"),
                name="playertypekillboard_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playertypekillboard",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("player", "enemy_aircraft"),
                name="playertypekillboard_alltime_unique",
            ),
        ),
    ]
