# Generated by Django 5.2.17 on 2026-10-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0028_site_custom_fonts"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="backfills_done",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
