# Generated by Django 5.2.17 on 2026-10-04 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0030_type_killboard_and_matchup_scopes"),
    ]

    operations = [
        migrations.CreateModel(
            name="AchievementHolders",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=32)),
                ("tier", models.PositiveSmallIntegerField()),
                ("holders", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("key", "tier"), name="achievement_holders_unique")],
            },
        ),
        migrations.CreateModel(
            name="PlayerAchievement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=32)),
                ("tier", models.PositiveSmallIntegerField()),
                ("earned_at", models.DateTimeField()),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="achievements", to="il2ks_db.mission"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="achievements", to="il2ks_db.player"
                    ),
                ),
                (
                    "sortie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="il2ks_db.playersortie",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["key", "tier", "-earned_at"], name="achievement_holders")],
                "constraints": [models.UniqueConstraint(fields=("player", "key", "tier"), name="achievement_unique")],
            },
        ),
    ]
