# Generated by Django 5.2.17 on 2026-10-04 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0030_type_killboard_and_matchup_scopes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftstats",
            name="attack_share",
        ),
        migrations.RemoveField(
            model_name="aircraftstats",
            name="kd",
        ),
        migrations.RemoveField(
            model_name="aircraftstats",
            name="kl",
        ),
        migrations.RemoveField(
            model_name="aircraftstats",
            name="survival",
        ),
    ]
