# Generated by Django 5.2.17 on 2026-10-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0033_achievements"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraftstats",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aircraftstats",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playeraircraft",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playermission",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerpool",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerpool",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertour",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertourpool",
            name="assists_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertourpool",
            name="assists_ground",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
