# Generated by Django 5.2.17 on 2026-10-04 11:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0035_accuracy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aircraftstats",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="player",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playeraircraft",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playermission",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playerpool",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playertour",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playertouraircraft",
            name="friendly_fire_incidents",
        ),
        migrations.RemoveField(
            model_name="playertourpool",
            name="friendly_fire_incidents",
        ),
    ]
