# Generated by Django 5.2.17 on 2026-10-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0036_drop_friendly_fire_incidents"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerkillboard",
            name="assists_received",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertourkillboard",
            name="assists_received",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PlayerStreakRun",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("since", models.DateTimeField()),
                ("until", models.DateTimeField()),
                (
                    "ended_by",
                    models.CharField(
                        choices=[("death", "Death"), ("captured", "Captured"), ("open", "Open")], max_length=8
                    ),
                ),
                (
                    "ended_sortie",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="il2ks_db.playersortie",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="streak_runs", to="il2ks_db.player"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streak_runs",
                        to="il2ks_db.tour",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["player", "tour", "-since"], name="streakruns_by_player_tour")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ended_by__in", ["death", "captured", "open"])), name="runs_end_valid"
                    )
                ],
            },
        ),
    ]
