# Generated by Django 5.2.17 on 2026-10-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0037_streak_runs_assists_received"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navlink",
            name="icon",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No icon"),
                    ("discord", "Discord"),
                    ("forum", "Forum"),
                    ("patreon", "Patreon"),
                    ("youtube", "YouTube"),
                    ("twitch", "Twitch"),
                    ("github", "GitHub"),
                    ("telegram", "Telegram"),
                    ("steam", "Steam"),
                    ("mail", "E-mail"),
                    ("book", "Rules / wiki"),
                    ("link", "Generic link"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
