# Generated by Django 5.2.17 on 2026-10-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0039_navlink_url_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="feature_alt",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_caption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image_height",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image_path",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image_small",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_image_width",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="feature_source_sig",
            field=models.CharField(blank=True, max_length=700),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_feature",
            field=models.CharField(
                choices=[
                    ("none", "Nothing (the normal front page)"),
                    ("image", "A large image from a file on the server"),
                ],
                default="none",
                max_length=10,
            ),
        ),
    ]
