# Generated by Django 5.2.17 on 2026-10-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0039_navlink_url_2000"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mission",
            name="mission_started_desc",
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(fields=["-started_at", "is_hidden", "sorties_total"], name="mission_started_list"),
        ),
        migrations.AddIndex(
            model_name="mission",
            index=models.Index(
                fields=["tour", "-started_at", "is_hidden", "sorties_total"], name="mission_tour_started_list"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["-score_air", "name_lower", "sorties", "is_hidden"], name="player_board_air"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-score_ground", "name_lower", "sorties", "is_hidden"], name="player_board_ground"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["-flight_time_s", "name_lower", "is_hidden"], name="player_board_playtime"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-elo_jet", "name_lower", "elo_jet_games", "is_hidden"], name="player_board_elo_jet"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["-elo_prop", "name_lower", "elo_prop_games", "is_hidden"], name="player_board_elo_prop"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["air_superiority_sorties", "flight_time_air_s", "is_hidden"], name="player_board_intercept"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["attack_sorties", "time_on_target_s", "is_hidden"], name="player_board_ground_hour"
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["-last_seen", "is_hidden"], name="player_list_last_seen"),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(fields=["-kills_air", "is_hidden"], name="player_list_kills_air"),
        ),
        migrations.AddIndex(
            model_name="playerbeststreak",
            index=models.Index(fields=["kind", "tour", "-sorties", "-kills_air"], name="bests_list"),
        ),
        migrations.AddIndex(
            model_name="playerpool",
            index=models.Index(fields=["propulsion"], name="playerpool_by_propulsion"),
        ),
    ]
