# Generated by Django 5.2.17 on 2026-10-04 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0039_navlink_url_2000"),
    ]

    operations = [
        migrations.CreateModel(
            name="TourAircraftStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_air_s", models.FloatField(default=0.0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("assists_air", models.PositiveIntegerField(default=0)),
                ("assists_ground", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("friendly_kills", models.PositiveIntegerField(default=0)),
                ("friendly_hits", models.PositiveIntegerField(default=0)),
                ("friendly_damage", models.FloatField(default=0.0)),
                ("taxi_accidents", models.PositiveIntegerField(default=0)),
                ("strafed_on_ground", models.PositiveIntegerField(default=0)),
                ("attack_sorties", models.PositiveIntegerField(default=0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("kills_tank_attack", models.PositiveIntegerField(default=0)),
                ("kills_ground_tank", models.PositiveIntegerField(default=0)),
                ("kills_ground_vehicle", models.PositiveIntegerField(default=0)),
                ("kills_ground_artillery", models.PositiveIntegerField(default=0)),
                ("kills_ground_aaa", models.PositiveIntegerField(default=0)),
                ("kills_ground_ship", models.PositiveIntegerField(default=0)),
                ("kills_ground_train", models.PositiveIntegerField(default=0)),
                ("kills_ground_building", models.PositiveIntegerField(default=0)),
                ("kills_ground_parked_aircraft", models.PositiveIntegerField(default=0)),
                ("kills_ground_other", models.PositiveIntegerField(default=0)),
                ("kills_ground_static", models.PositiveIntegerField(default=0)),
                ("kills_air_pvp", models.PositiveIntegerField(default=0)),
                ("kills_air_ai", models.PositiveIntegerField(default=0)),
                ("deaths_by_player", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("deaths_by_aaa", models.PositiveIntegerField(default=0)),
                ("deaths_by_ground", models.PositiveIntegerField(default=0)),
                ("deaths_by_friendly", models.PositiveIntegerField(default=0)),
                ("deaths_by_environment", models.PositiveIntegerField(default=0)),
                ("deaths_by_unknown", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_player", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_aaa", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ground", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_friendly", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_environment", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_unknown", models.PositiveIntegerField(default=0)),
                ("score_air", models.FloatField(default=0.0)),
                ("score_ground", models.FloatField(default=0.0)),
                ("score_ground_attack", models.FloatField(default=0.0)),
                ("air_superiority_sorties", models.PositiveIntegerField(default=0)),
                ("kills_intercept", models.PositiveIntegerField(default=0)),
                ("accuracy_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_hits", models.PositiveIntegerField(default=0)),
                ("accuracy_air_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_air_hits", models.PositiveIntegerField(default=0)),
                ("accuracy_ground_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_ground_hits", models.PositiveIntegerField(default=0)),
                ("gun_hits_air", models.PositiveIntegerField(default=0)),
                ("gun_hits_ground", models.PositiveIntegerField(default=0)),
                ("pilots", models.PositiveIntegerField(default=0)),
                ("side", models.CharField(blank=True, default="", max_length=8)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="tour_stats", to="il2ks_db.gameobject"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_stats", to="il2ks_db.tour"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [models.UniqueConstraint(fields=("tour", "aircraft"), name="touraircraftstats_unique")],
            },
        ),
    ]
