# Generated by Django 5.2.17 on 2026-10-04 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0040_tour_aircraft_stats"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="aircraftpayload",
            name="aircraftpayload_unique",
        ),
        migrations.RemoveConstraint(
            model_name="touraircraftstats",
            name="touraircraftstats_unique",
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="combat_role",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="elo_avg",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="flight_time_s",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="kills_air_pvp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="score_ground_attack",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="time_on_target_s",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="touraircraftstats",
            name="role",
            field=models.CharField(
                choices=[("all", "All"), ("air_superiority", "Air Superiority"), ("attack", "Attack")],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="touraircraftstats",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aircraft_stats",
                to="il2ks_db.tour",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftpayload",
            constraint=models.UniqueConstraint(
                fields=("aircraft", "payload_name", "combat_role"), name="aircraftpayload_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "role"),
                name="touraircraftstats_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "role"),
                name="touraircraftstats_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.CheckConstraint(
                condition=models.Q(("tour__isnull", False), models.Q(("role", "all"), _negated=True), _connector="OR"),
                name="touraircraftstats_alltime_role",
            ),
        ),
    ]
