# Generated by Django 5.2.17 on 2026-10-04 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0040_tour_aircraft_stats"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftAmmoMixStats",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mix", models.CharField(max_length=512)),
                ("ammo", models.CharField(max_length=128)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ammo_mix_stats",
                        to="il2ks_db.gameobject",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("aircraft", "mix", "ammo"), name="aircraftammomixstats_unique")
                ],
            },
        ),
        migrations.CreateModel(
            name="MissionAircraftAmmoMix",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("mix", models.CharField(max_length=512)),
                ("ammo", models.CharField(max_length=128)),
                ("kills", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mission_ammo_mixes",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aircraft_ammo_mixes",
                        to="il2ks_db.mission",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("mission", "aircraft", "mix", "ammo"), name="missionaircraftammomix_unique"
                    )
                ],
            },
        ),
    ]
