# Generated by Django 5.2.17 on 2026-10-04 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0041_ammo_mixes"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerAircraftBuild",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("payload", "Loadout"), ("mods", "Weapon modifications"), ("ammo", "Gun ammo hits")],
                        max_length=8,
                    ),
                ),
                ("value", models.BigIntegerField(default=0)),
                ("label", models.CharField(blank=True, max_length=128)),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "aircraft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_build_rows",
                        to="il2ks_db.gameobject",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="build_rows", to="il2ks_db.player"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="build_rows",
                        to="il2ks_db.tour",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["player", "tour"], name="playeraircraftbuild_by_player")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", True)),
                        fields=("player", "aircraft", "kind", "value", "label"),
                        name="playeraircraftbuild_unique_all",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", False)),
                        fields=("player", "aircraft", "tour", "kind", "value", "label"),
                        name="playeraircraftbuild_unique_tour",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SortieGunHits",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ammo", models.CharField(max_length=128)),
                ("hits", models.PositiveIntegerField(default=0)),
                (
                    "sortie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gun_hit_rows",
                        to="il2ks_db.playersortie",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("sortie", "ammo"), name="sortiegunhits_unique")],
            },
        ),
    ]
