# Generated by Django 5.2.17 on 2026-10-04 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0042_player_aircraft_build"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="achievementholders",
            name="achievement_holders_unique",
        ),
        migrations.RemoveConstraint(
            model_name="playerachievement",
            name="achievement_unique",
        ),
        migrations.RemoveIndex(
            model_name="playerachievement",
            name="achievement_holders",
        ),
        migrations.AddField(
            model_name="achievementholders",
            name="pilots",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="achievementholders",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievement_holders",
                to="il2ks_db.tour",
            ),
        ),
        migrations.AddField(
            model_name="playerachievement",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="achievements", to="il2ks_db.tour"
            ),
        ),
        migrations.AddIndex(
            model_name="playerachievement",
            index=models.Index(fields=["tour", "key", "tier", "-earned_at"], name="achievement_holders_tour"),
        ),
        migrations.AddIndex(
            model_name="playerachievement",
            index=models.Index(fields=["tour", "-earned_at"], name="achievement_feed"),
        ),
        migrations.AddConstraint(
            model_name="achievementholders",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "key", "tier"),
                name="achievement_holders_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="achievementholders",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)), fields=("key", "tier"), name="achievement_holders_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerachievement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("player", "tour", "key", "tier"),
                name="achievement_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerachievement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)), fields=("player", "key", "tier"), name="achievement_unique"
            ),
        ),
    ]
