# Generated by Django 5.2.17 on 2026-10-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0043_achievements_per_tour"),
    ]

    operations = [
        migrations.AddField(
            model_name="playersortie",
            name="elo_peak",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="first_blood",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="multi_kill",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playersortie",
            name="rams",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
