# Generated by Django 5.2.17 on 2026-10-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0045_payload_names_refresh"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="quips",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="quips_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
