# Generated by Django 5.2.17 on 2026-10-04 17:54

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def drop_filter_rows(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Going back removes the modification-filter rows first: without the `mod_pattern` column they would duplicate the
    unfiltered rows and break the older unique constraints."""
    for name in ("TourAircraftStats", "AircraftPayload"):
        apps.get_model("il2ks_db", name).objects.exclude(mod_pattern="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0047_aircraft_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="AircraftMods",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("combat_role", models.CharField(blank=True, default="", max_length=16)),
                ("mod_pattern", models.CharField(blank=True, default="", max_length=16)),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("kills_air_pvp", models.PositiveIntegerField(default=0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("score_ground_attack", models.FloatField(default=0.0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("elo_avg", models.FloatField(blank=True, null=True)),
                ("weapon_mods", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="aircraftpayload",
            name="aircraftpayload_unique",
        ),
        migrations.RemoveConstraint(
            model_name="touraircraftstats",
            name="touraircraftstats_unique",
        ),
        migrations.RemoveConstraint(
            model_name="touraircraftstats",
            name="touraircraftstats_alltime_unique",
        ),
        migrations.RemoveConstraint(
            model_name="touraircraftstats",
            name="touraircraftstats_alltime_role",
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="mod_pattern",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="touraircraftstats",
            name="mod_pattern",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddConstraint(
            model_name="aircraftpayload",
            constraint=models.UniqueConstraint(
                fields=("aircraft", "payload_name", "combat_role", "mod_pattern"), name="aircraftpayload_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "role", "mod_pattern"),
                name="touraircraftstats_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "role", "mod_pattern"),
                name="touraircraftstats_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="touraircraftstats",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("tour__isnull", False),
                    models.Q(("role", "all"), _negated=True),
                    models.Q(("mod_pattern", ""), _negated=True),
                    _connector="OR",
                ),
                name="touraircraftstats_alltime_role",
            ),
        ),
        migrations.AddField(
            model_name="aircraftmods",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="mods_stats", to="il2ks_db.gameobject"
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmods",
            constraint=models.UniqueConstraint(
                fields=("aircraft", "weapon_mods", "combat_role", "mod_pattern"), name="aircraftmods_unique"
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, drop_filter_rows),  # reverse runs first
    ]
