# Generated by Django 5.2.17 on 2026-10-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0050_delete_build_mods_ammo_rows"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="playeraircraftbuild",
            name="hits",
        ),
        migrations.AlterField(
            model_name="playeraircraftbuild",
            name="kind",
            field=models.CharField(choices=[("payload", "Loadout")], max_length=8),
        ),
        migrations.DeleteModel(
            name="SortieGunHits",
        ),
    ]
