# Generated by Django 5.2.17 on 2026-10-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0053_drop_gun_hits_and_build_extras"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="is_live",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="show_live_sorties",
            field=models.BooleanField(default=True),
        ),
    ]
