# Generated by Django 5.2.17 on 2026-10-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0054_live_sorties"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="achievements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="achievements_applied",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
