# Generated by Django 5.2.17 on 2026-10-04 19:47

import django.db.models.deletion
from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def drop_scoped_rows(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Going back removes the scope rows first: without the new columns they would duplicate the all-time rows and break
    the older unique constraints (the rebuild recreates what is left)."""
    for name in ("AircraftPayload", "AircraftMods", "AircraftAmmoStats", "AircraftAmmoMixStats"):
        apps.get_model("il2ks_db", name).objects.exclude(tour=None).delete()
    for name in ("AircraftAmmoStats", "AircraftAmmoMixStats"):
        apps.get_model("il2ks_db", name).objects.exclude(role="all", mod_pattern="").delete()
    apps.get_model("il2ks_db", "AircraftMatchup").objects.exclude(scoped_side="").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0056_site_achievements"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerAircraftScope",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sorties", models.PositiveIntegerField(default=0)),
                ("flight_time_air_s", models.FloatField(default=0.0)),
                ("flight_time_s", models.FloatField(default=0.0)),
                ("kills_air", models.PositiveIntegerField(default=0)),
                ("kills_ground", models.PositiveIntegerField(default=0)),
                ("assists", models.PositiveIntegerField(default=0)),
                ("assists_air", models.PositiveIntegerField(default=0)),
                ("assists_ground", models.PositiveIntegerField(default=0)),
                ("deaths", models.PositiveIntegerField(default=0)),
                ("planes_lost", models.PositiveIntegerField(default=0)),
                ("bailouts", models.PositiveIntegerField(default=0)),
                ("suspected_early_bailouts", models.PositiveIntegerField(default=0)),
                ("captures", models.PositiveIntegerField(default=0)),
                ("takeoffs", models.PositiveIntegerField(default=0)),
                ("landings", models.PositiveIntegerField(default=0)),
                ("friendly_kills", models.PositiveIntegerField(default=0)),
                ("friendly_hits", models.PositiveIntegerField(default=0)),
                ("friendly_damage", models.FloatField(default=0.0)),
                ("taxi_accidents", models.PositiveIntegerField(default=0)),
                ("strafed_on_ground", models.PositiveIntegerField(default=0)),
                ("attack_sorties", models.PositiveIntegerField(default=0)),
                ("time_on_target_s", models.FloatField(default=0.0)),
                ("kills_tank_attack", models.PositiveIntegerField(default=0)),
                ("kills_ground_tank", models.PositiveIntegerField(default=0)),
                ("kills_ground_vehicle", models.PositiveIntegerField(default=0)),
                ("kills_ground_artillery", models.PositiveIntegerField(default=0)),
                ("kills_ground_aaa", models.PositiveIntegerField(default=0)),
                ("kills_ground_ship", models.PositiveIntegerField(default=0)),
                ("kills_ground_train", models.PositiveIntegerField(default=0)),
                ("kills_ground_building", models.PositiveIntegerField(default=0)),
                ("kills_ground_parked_aircraft", models.PositiveIntegerField(default=0)),
                ("kills_ground_other", models.PositiveIntegerField(default=0)),
                ("kills_ground_static", models.PositiveIntegerField(default=0)),
                ("kills_air_pvp", models.PositiveIntegerField(default=0)),
                ("kills_air_ai", models.PositiveIntegerField(default=0)),
                ("deaths_by_player", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("deaths_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("deaths_by_aaa", models.PositiveIntegerField(default=0)),
                ("deaths_by_ground", models.PositiveIntegerField(default=0)),
                ("deaths_by_friendly", models.PositiveIntegerField(default=0)),
                ("deaths_by_environment", models.PositiveIntegerField(default=0)),
                ("deaths_by_unknown", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_player", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_aircraft", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ai_gunner", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_aaa", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_ground", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_friendly", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_environment", models.PositiveIntegerField(default=0)),
                ("planes_lost_by_unknown", models.PositiveIntegerField(default=0)),
                ("score_air", models.FloatField(default=0.0)),
                ("score_ground", models.FloatField(default=0.0)),
                ("score_ground_attack", models.FloatField(default=0.0)),
                ("air_superiority_sorties", models.PositiveIntegerField(default=0)),
                ("kills_intercept", models.PositiveIntegerField(default=0)),
                ("accuracy_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_hits", models.PositiveIntegerField(default=0)),
                ("accuracy_air_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_air_hits", models.PositiveIntegerField(default=0)),
                ("accuracy_ground_rounds", models.PositiveIntegerField(default=0)),
                ("accuracy_ground_hits", models.PositiveIntegerField(default=0)),
                ("gun_hits_air", models.PositiveIntegerField(default=0)),
                ("gun_hits_ground", models.PositiveIntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[("all", "All"), ("air_superiority", "Air Superiority"), ("attack", "Attack")],
                        default="all",
                        max_length=16,
                    ),
                ),
                ("mod_pattern", models.CharField(blank=True, default="", max_length=16)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="aircraftammomixstats",
            name="aircraftammomixstats_unique",
        ),
        migrations.RemoveConstraint(
            model_name="aircraftammostats",
            name="aircraftammostats_unique",
        ),
        migrations.RemoveConstraint(
            model_name="aircraftmatchup",
            name="aircraftmatchup_tour_unique",
        ),
        migrations.RemoveConstraint(
            model_name="aircraftmatchup",
            name="aircraftmatchup_alltime_unique",
        ),
        migrations.RemoveConstraint(
            model_name="aircraftmods",
            name="aircraftmods_unique",
        ),
        migrations.RemoveConstraint(
            model_name="aircraftpayload",
            name="aircraftpayload_unique",
        ),
        migrations.RemoveConstraint(
            model_name="missionaircraftammo",
            name="missionaircraftammo_unique",
        ),
        migrations.RemoveConstraint(
            model_name="missionaircraftammomix",
            name="missionaircraftammomix_unique",
        ),
        migrations.AddField(
            model_name="aircraftammomixstats",
            name="mod_pattern",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="aircraftammomixstats",
            name="role",
            field=models.CharField(
                choices=[("all", "All"), ("air_superiority", "Air Superiority"), ("attack", "Attack")],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="aircraftammomixstats",
            name="tour",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ammo_mix_stats",
                to="il2ks_db.tour",
            ),
        ),
        migrations.AddField(
            model_name="aircraftammostats",
            name="mod_pattern",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="aircraftammostats",
            name="role",
            field=models.CharField(
                choices=[("all", "All"), ("air_superiority", "Air Superiority"), ("attack", "Attack")],
                default="all",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="aircraftammostats",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="ammo_stats", to="il2ks_db.tour"
            ),
        ),
        migrations.AddField(
            model_name="aircraftmatchup",
            name="combat_role",
            field=models.CharField(default="all", max_length=16),
        ),
        migrations.AddField(
            model_name="aircraftmatchup",
            name="mod_pattern",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="aircraftmatchup",
            name="scoped_side",
            field=models.CharField(blank=True, default="", max_length=6),
        ),
        migrations.AddField(
            model_name="aircraftmods",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.tour"
            ),
        ),
        migrations.AddField(
            model_name="aircraftpayload",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.tour"
            ),
        ),
        migrations.AddField(
            model_name="missionaircraftammo",
            name="combat_role",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="missionaircraftammo",
            name="weapon_mods",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="missionaircraftammomix",
            name="combat_role",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="missionaircraftammomix",
            name="weapon_mods",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddConstraint(
            model_name="aircraftammomixstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "role", "mod_pattern", "mix", "ammo"),
                name="aircraftammomixstats_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftammomixstats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "role", "mod_pattern", "mix", "ammo"),
                name="aircraftammomixstats_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftammostats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "role", "mod_pattern", "ammo"),
                name="aircraftammostats_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftammostats",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "role", "mod_pattern", "ammo"),
                name="aircraftammostats_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmatchup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=(
                    "tour",
                    "killer_aircraft",
                    "victim_aircraft",
                    "intercept",
                    "scoped_side",
                    "combat_role",
                    "mod_pattern",
                ),
                name="aircraftmatchup_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmatchup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("killer_aircraft", "victim_aircraft", "intercept", "scoped_side", "combat_role", "mod_pattern"),
                name="aircraftmatchup_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmods",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "weapon_mods", "combat_role", "mod_pattern"),
                name="aircraftmods_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftmods",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "weapon_mods", "combat_role", "mod_pattern"),
                name="aircraftmods_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftpayload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "payload_name", "combat_role", "mod_pattern"),
                name="aircraftpayload_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="aircraftpayload",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "payload_name", "combat_role", "mod_pattern"),
                name="aircraftpayload_alltime_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="missionaircraftammo",
            constraint=models.UniqueConstraint(
                fields=("mission", "aircraft", "combat_role", "weapon_mods", "ammo"), name="missionaircraftammo_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="missionaircraftammomix",
            constraint=models.UniqueConstraint(
                fields=("mission", "aircraft", "combat_role", "weapon_mods", "mix", "ammo"),
                name="missionaircraftammomix_unique",
            ),
        ),
        migrations.AddField(
            model_name="playeraircraftscope",
            name="aircraft",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="player_scopes", to="il2ks_db.gameobject"
            ),
        ),
        migrations.AddField(
            model_name="playeraircraftscope",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="aircraft_scopes", to="il2ks_db.player"
            ),
        ),
        migrations.AddField(
            model_name="playeraircraftscope",
            name="tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="il2ks_db.tour"
            ),
        ),
        migrations.AddIndex(
            model_name="playeraircraftscope",
            index=models.Index(fields=["aircraft", "tour", "role", "mod_pattern"], name="aircraftscope_by_aircraft"),
        ),
        migrations.AddConstraint(
            model_name="playeraircraftscope",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("tour", "aircraft", "player", "role", "mod_pattern"),
                name="playeraircraftscope_tour_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playeraircraftscope",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("aircraft", "player", "role", "mod_pattern"),
                name="playeraircraftscope_alltime_unique",
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, drop_scoped_rows),  # reverse runs first
    ]
