# Generated by Django 5.2.17 on 2026-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0059_site_level2_pending"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertouraircraft",
            name="elo",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="playertouraircraft",
            name="elo_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playertourpool",
            name="elo",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="playertourpool",
            name="elo_games",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
