# Generated by Django 5.2.17 on 2026-10-05 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0060_tour_elo"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerstreak",
            name="current_tour",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="il2ks_db.tour"
            ),
        ),
    ]
