# Generated by Django 5.2.17 on 2026-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0062_site_score_flight"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="result",
            field=models.CharField(default="unknown", max_length=8),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tour_on_win",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="tour_on_win_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tour",
            name="by_win",
            field=models.BooleanField(default=False),
        ),
    ]
