# Generated by Django 5.2.17 on 2026-10-05 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0063_tour_on_win"),
    ]

    operations = [
        migrations.AddField(
            model_name="playertypekillboard",
            name="deaths_in_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="playertypekillboard",
            name="kills_with_counts",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="PlayerTourName",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=128)),
                ("first_seen", models.DateTimeField()),
                ("last_seen", models.DateTimeField()),
                ("last_spawn", models.DateTimeField()),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tour_names", to="il2ks_db.player"
                    ),
                ),
                (
                    "tour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="player_names", to="il2ks_db.tour"
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("player", "tour", "name"), name="playertourname_unique")
                ],
            },
        ),
    ]
