# Generated by Django 5.2.17 on 2026-10-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0067_player_role_totals"),
    ]

    operations = [
        migrations.AddField(
            model_name="aircraftstats",
            name="elo",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="aircraftstats",
            name="elo_games",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="touraircraftstats",
            name="elo",
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name="touraircraftstats",
            name="elo_games",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
