# Generated by Django 5.2.17 on 2026-10-05 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0068_aircraft_type_elo"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playerbeststreak",
            name="bests_tour_unique",
        ),
        migrations.RemoveConstraint(
            model_name="playerbeststreak",
            name="bests_alltime_unique",
        ),
        migrations.RemoveConstraint(
            model_name="playerbeststreak",
            name="bests_kind_valid",
        ),
        migrations.RemoveIndex(
            model_name="playerbeststreak",
            name="bests_list",
        ),
        migrations.RemoveIndex(
            model_name="playerbeststreak",
            name="bests_alltime_list",
        ),
        migrations.RemoveIndex(
            model_name="playerstreak",
            name="streak_current_desc",
        ),
        migrations.RemoveIndex(
            model_name="playerstreakrun",
            name="streakruns_by_player_tour",
        ),
        migrations.RemoveIndex(
            model_name="playerstreakrun",
            name="streakruns_alltime",
        ),
        migrations.AddField(
            model_name="player",
            name="streak_kills_air",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="player",
            name="streak_kills_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerbeststreak",
            name="kills_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerbeststreak",
            name="track",
            field=models.CharField(choices=[("air", "Air"), ("ground", "Ground")], default="air", max_length=6),
        ),
        migrations.AddField(
            model_name="playerstreak",
            name="best_kills_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstreak",
            name="current_kills_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstreak",
            name="track",
            field=models.CharField(choices=[("air", "Air"), ("ground", "Ground")], default="air", max_length=6),
        ),
        migrations.AddField(
            model_name="playerstreakrun",
            name="kills_ground",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerstreakrun",
            name="track",
            field=models.CharField(choices=[("air", "Air"), ("ground", "Ground")], default="air", max_length=6),
        ),
        migrations.AlterField(
            model_name="playerbeststreak",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sorties", "Sorties"),
                    ("air_kills", "Air Kills"),
                    ("flight_time", "Flight Time"),
                    ("ground_kills", "Ground Kills"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="playerstreak",
            name="player",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="streaks", to="il2ks_db.player"
            ),
        ),
        migrations.AddIndex(
            model_name="playerbeststreak",
            index=models.Index(fields=["track", "kind", "tour", "-sorties", "-kills_air"], name="bests_track_list"),
        ),
        migrations.AddIndex(
            model_name="playerbeststreak",
            index=models.Index(
                condition=models.Q(("tour__isnull", True)),
                fields=["track", "kind", "-sorties", "-kills_air", "id"],
                name="bests_alltime_track_list",
            ),
        ),
        migrations.AddIndex(
            model_name="playerstreak",
            index=models.Index(fields=["track", "-current_sorties"], name="streak_track_current_desc"),
        ),
        migrations.AddIndex(
            model_name="playerstreakrun",
            index=models.Index(fields=["player", "tour", "track", "-since"], name="streakruns_track_player_tour"),
        ),
        migrations.AddIndex(
            model_name="playerstreakrun",
            index=models.Index(
                condition=models.Q(("tour__isnull", True)),
                fields=["player", "track", "-since", "-id"],
                name="streakruns_track_alltime",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", False)),
                fields=("player", "tour", "track", "kind"),
                name="bests_tour_track_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.UniqueConstraint(
                condition=models.Q(("tour__isnull", True)),
                fields=("player", "track", "kind"),
                name="bests_alltime_track_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["sorties", "air_kills", "flight_time", "ground_kills"])),
                name="bests_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["air", "ground"])), name="bests_track_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstreak",
            constraint=models.UniqueConstraint(fields=("player", "track"), name="streak_player_track_unique"),
        ),
        migrations.AddConstraint(
            model_name="playerstreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["air", "ground"])), name="streak_track_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstreakrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["air", "ground"])), name="runs_track_valid"
            ),
        ),
    ]
