# Generated by Django 5.2.17 on 2026-10-05 14:06

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def nothing(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Forwards: the all-track rows are written by the next ingest or rebuild, nothing to move."""


def drop_all_track_rows(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    """Backwards: 0069 knows only the air and ground tracks and no `kills` kind, so the rows of the all track (and the
    `kills` rows) go before the narrower check constraints come back. A rebuild writes them again."""
    for name in ("PlayerStreak", "PlayerStreakRun", "PlayerBestStreak"):
        apps.get_model("il2ks_db", name).objects.filter(track="all").delete()
    apps.get_model("il2ks_db", "PlayerBestStreak").objects.filter(kind="kills").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0069_streak_tracks"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="playerbeststreak",
            name="bests_kind_valid",
        ),
        migrations.RemoveConstraint(
            model_name="playerbeststreak",
            name="bests_track_valid",
        ),
        migrations.RemoveConstraint(
            model_name="playerstreak",
            name="streak_track_valid",
        ),
        migrations.RemoveConstraint(
            model_name="playerstreakrun",
            name="runs_track_valid",
        ),
        migrations.AlterField(
            model_name="playerbeststreak",
            name="kind",
            field=models.CharField(
                choices=[
                    ("sorties", "Sorties"),
                    ("air_kills", "Air Kills"),
                    ("flight_time", "Flight Time"),
                    ("ground_kills", "Ground Kills"),
                    ("kills", "Kills"),
                ],
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="playerbeststreak",
            name="track",
            field=models.CharField(
                choices=[("all", "All"), ("air", "Air"), ("ground", "Ground")], default="air", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="playerstreak",
            name="track",
            field=models.CharField(
                choices=[("all", "All"), ("air", "Air"), ("ground", "Ground")], default="air", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="playerstreakrun",
            name="track",
            field=models.CharField(
                choices=[("all", "All"), ("air", "Air"), ("ground", "Ground")], default="air", max_length=6
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("kind__in", ["sorties", "air_kills", "flight_time", "ground_kills", "kills"])),
                name="bests_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="playerbeststreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["all", "air", "ground"])), name="bests_track_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstreak",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["all", "air", "ground"])), name="streak_track_valid"
            ),
        ),
        migrations.AddConstraint(
            model_name="playerstreakrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("track__in", ["all", "air", "ground"])), name="runs_track_valid"
            ),
        ),
        # Last, so that backwards it runs first: the rows go before the constraints are added again.
        migrations.RunPython(nothing, drop_all_track_rows),
    ]
