# Generated by Django 5.2.17 on 2026-10-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0076_sortie_tour"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="backfills_done",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="catalog_fingerprint",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
