# Generated by Django 5.2.17 on 2026-10-05 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0069_streak_tracks"),
    ]

    operations = [
        migrations.AddField(
            model_name="statthreshold",
            name="p95",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="statthreshold",
            name="p99",
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name="SortieThreshold",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metric", models.CharField(max_length=16)),
                ("population", models.PositiveIntegerField()),
                ("histogram", models.JSONField(default=dict)),
                ("p10", models.FloatField(default=0.0)),
                ("p25", models.FloatField(default=0.0)),
                ("p50", models.FloatField(default=0.0)),
                ("p75", models.FloatField(default=0.0)),
                ("p90", models.FloatField(default=0.0)),
                ("p95", models.FloatField(default=0.0)),
                ("p99", models.FloatField(default=0.0)),
                (
                    "tour",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sortie_thresholds",
                        to="il2ks_db.tour",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", False)),
                        fields=("tour", "metric"),
                        name="sortiethreshold_tour_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("tour__isnull", True)),
                        fields=("metric",),
                        name="sortiethreshold_alltime_unique",
                    ),
                ],
            },
        ),
    ]
