# Generated by Django 5.2.17 on 2026-10-05 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0071_stat_threshold_top_tiers"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="favicon",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="favicon_custom",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_bg_image",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_bg_position",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("left", "Left"),
                    ("right", "Right"),
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                ],
                default="center",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="header_bg_shade",
            field=models.PositiveSmallIntegerField(
                default=70,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)],
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_bg_image",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_bg_position",
            field=models.CharField(
                choices=[
                    ("center", "Center"),
                    ("left", "Left"),
                    ("right", "Right"),
                    ("top", "Top"),
                    ("bottom", "Bottom"),
                ],
                default="center",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="home_bg_shade",
            field=models.PositiveSmallIntegerField(
                default=70,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)],
            ),
        ),
    ]
