# Generated by Django 5.2.17 on 2026-10-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("il2ks_db", "0071_stat_threshold_top_tiers"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="playersortie",
            index=models.Index(fields=["-spawned_at", "-id", "role", "mission", "player"], name="sortie_recent"),
        ),
        migrations.AddIndex(
            model_name="playersortie",
            index=models.Index(fields=["aircraft", "-spawned_at", "-id"], name="sortie_aircraft_recent"),
        ),
    ]
