"""Inventory of every image the site uses or ships (doc 15, the designer brief): `il2ks dev assets`.

The manifest below is the one list of files the brief promises a designer. It is cross-checked against what the code
references (templates, CSS, Python icon maps) and what is on disk under `static/il2ks/img/`, and the brief's
"Complete file inventory" section is generated from it, so the three cannot silently drift
(`tests/unit/test_asset_inventory.py`). Commands: `il2ks dev assets` (print), `--check` (exit 1 on drift),
`--write` (rewrite the brief's generated section).
"""

import re
from collections.abc import Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from il2ks.core.catalog.loader import GROUND_CATEGORIES, load_default_catalog
from il2ks.db.models import BluforEmblem, RedforEmblem
from il2ks.web import display, sortie_view
from il2ks.web.ground import GROUND_ICONS
from il2ks.web.icons import slug

WEB_DIR = Path(__file__).resolve().parents[1] / "web"
IMG_DIR = WEB_DIR / "static" / "il2ks" / "img"
README = IMG_DIR / "README.md"
BRIEF_NAME = "15_visual_assets.md"
START = "<!-- inventory:start (generated by `uv run il2ks dev assets --write`; do not edit by hand) -->"
END = "<!-- inventory:end -->"

type Status = Literal["shipped", "planned", "missing", "unused"]
type Priority = Literal["P1", "P2", "P3"]

ICON = "SVG 24 x 24, currentColor"
GROUPS = (
    "brand",
    "aircraft",
    "coalition",
    "outcome",
    "event",
    "ground",
    "role",
    "stat",
    "medal",
    "nav",
    "flag",
    "pattern",
    "illustration",
)
GROUP_TITLES = {
    "brand": "Brand (`brand/`)",
    "aircraft": "Aircraft (`aircraft/`)",
    "coalition": "Coalitions (`coalition/`)",
    "outcome": "Sortie outcome and pilot fate (`outcome/`)",
    "event": "Timeline events (`event/`)",
    "ground": "Ground targets (`ground/`)",
    "role": "Combat role (`role/`)",
    "stat": "Stat tiles (`stat/`)",
    "medal": "Achievement medals (`medal/`)",
    "nav": "Navigation link icons (`nav/`)",
    "flag": "Language flags (`flag/`)",
    "pattern": "Textures (`pattern/`)",
    "illustration": "Illustrations (`illustration/`)",
}
# Not Tabler: original drawings (README.md "Ours"). Everything else must be a row of the README's Tabler table.
OURS = (
    "aircraft/",
    "brand/",
    "coalition/insignia/",
    "pattern/",
    "illustration/",
    "ground/artillery.svg",
    "ground/aaa.svg",
    "flag/",  # flag-icons (MIT) and a hand-reduced Spain; README.md "Flags"
)


NAV_ICONS = (
    "discord",
    "forum",
    "patreon",
    "youtube",
    "twitch",
    "github",
    "telegram",
    "steam",
    "mail",
    "book",
    "link",
)


@dataclass(frozen=True)
class Asset:
    path: str  # relative to static/il2ks/img/
    used_in: str
    size: str
    priority: Priority
    release: bool  # must exist (and be wired) for the first release; a placeholder is enough
    dynamic: bool = False  # loaded by a computed name (insignia choice, aircraft slug), so no literal reference

    @property
    def group(self) -> str:
        return self.path.split("/", 1)[0]


# --- the manifest ------------------------------------------------------------------------------------------------


def _outcome_usage() -> dict[str, str]:
    """outcome/<name> -> the labels (display.py badge tables) that use it."""
    usage: dict[str, list[str]] = {}
    for table, where in (
        (display.OUTCOMES, "sortie outcome"),
        (display.FATES, "pilot fate"),
        (display.STATUSES, "pilot status"),
    ):
        for key, (_label, _tone, icon) in table.items():
            if not icon:
                continue
            usage.setdefault(f"{icon}.svg", []).append(f"{where} `{key}`")
    return {path: "; ".join(parts) for path, parts in usage.items()}


def build_manifest() -> list[Asset]:
    assets: list[Asset] = []

    def add(path: str, used_in: str, size: str, priority: Priority, release: bool, dynamic: bool = False) -> None:
        assets.append(Asset(path, used_in, size, priority, release, dynamic))

    # brand
    add(
        "brand/logo-mark.svg",
        "Header (about 40 px high) when no logo is uploaded; home page hero, faint",
        "SVG, viewBox 64, scales to 512",
        "P1",
        True,
    )
    add("brand/favicon.svg", "Browser tab icon (`base.html` `<link rel=icon>`)", "SVG, viewBox 64", "P1", True)
    add(
        "brand/favicon-32.png",
        "Fallback tab icon for browsers without SVG favicons (not wired yet)",
        "PNG 32 x 32",
        "P1",
        False,
    )
    add("brand/apple-touch-icon.png", "iOS home-screen icon (not wired yet)", "PNG 180 x 180", "P1", False)
    add("brand/icon-512.png", "Web-app / large icon (not wired yet)", "PNG 512 x 512", "P2", False)
    add(
        "brand/og-default.png",
        "Link preview (`og:image`) when a sortie is shared; the tag is added once the file exists",
        "PNG 1200 x 630",
        "P1",
        False,
        True,
    )

    # aircraft
    for name, where in (
        ("generic-jet", "Fallback for a jet without its own file (`aircraft_icon` tag)"),
        ("generic-prop", "Fallback for a propeller aircraft without its own file"),
        ("unknown", "Fallback when the propulsion is unknown"),
    ):
        add(f"aircraft/{name}.svg", f"{where}: tables, sortie header, aircraft pages", ICON, "P1", True)
    catalog = load_default_catalog()
    playable = sorted(
        {slug(o.log_name) for o in catalog.objects() if o.is_playable and o.cls in ("fighter", "attacker")}
    )
    ai_types = sorted(
        {slug(o.log_name) for o in catalog.objects() if o.cls in ("bomber", "transport") and not o.is_playable}
    )
    for name in playable:
        add(
            f"aircraft/{name}.svg",
            f"Own icon of a playable type, picked by log-name slug (`{name}`)",
            ICON,
            "P2",
            False,
            True,
        )
    for name in ai_types:
        add(
            f"aircraft/{name}.svg",
            f"Own icon of an AI-only type (`{name}`), e.g. in the sortie timeline",
            ICON,
            "P3",
            False,
            True,
        )
    for name in playable:
        add(
            f"aircraft/{name}-profile.svg",
            f"Side profile of `{name}` for the sortie page header (not wired yet)",
            "SVG, about 480 x 160, 2-3 tones",
            "P3",
            False,
            True,
        )

    # coalitions
    for side in ("redfor", "blufor"):
        add(
            f"coalition/{side}.svg",
            f"Neutral {side.upper()} emblem: side badges, tables, mission page (`coalition_icon` tag)",
            ICON,
            "P2",
            True,
            True,
        )
    for emblem in (*RedforEmblem.values, *BluforEmblem.values):
        if emblem != "neutral":
            add(
                f"coalition/insignia/{emblem}.svg",
                f"Optional insignia `{emblem}`, chosen in the site settings, replaces the neutral emblem",
                ICON + " (own colours allowed)",
                "P2",
                False,
                True,
            )

    # outcome / fate
    usage = _outcome_usage()
    outcome_names = sorted({p.removesuffix(".svg") for p in usage})
    extra_usage = {"outcome/dead": "pilot status `dead`; also the timeline rows `killed` and `died`"}
    outcome_names = sorted({*outcome_names, "outcome/mission-ended"})
    usage.setdefault("outcome/mission-ended.svg", "reserved for a mission-ended outcome, no outcome value uses it yet")
    for name in outcome_names:
        used = extra_usage.get(name, usage[f"{name}.svg"])
        add(
            f"{name}.svg",
            f"Badge: {used} (sortie tables, sortie page, profile)",
            ICON,
            "P1",
            name != "outcome/mission-ended",
        )

    # events (sortie timeline)
    event_icons = {icon for icon in sortie_view.EVENT_ICONS.values() if icon.startswith("event/")} | {
        "event/kill-ground"
    }
    for name in sorted(event_icons):
        add(f"{name}.svg", "Sortie page timeline row", ICON, "P2", True)

    # ground
    for category in GROUND_CATEGORIES:
        add(
            f"{GROUND_ICONS[category]}.svg",
            f"Ground-kill breakdown (profile, sortie page): category `{category}`; also timeline rows",
            ICON,
            "P2",
            True,
        )

    # roles
    for name, text in (("air-superiority", "guns only"), ("attack", "bombs / rockets / napalm")):
        add(f"role/{name}.svg", f"Sortie role badge ({text})", ICON, "P2", True)

    # stat tiles
    stat_uses = {
        "sorties": "Profile, aircraft, mission and home tiles",
        "flight-time": "Profile, aircraft and mission tiles",
        "air-kills": "Profile, aircraft, mission and home tiles",
        "ground-kills": "Profile, aircraft, mission and home tiles",
        "assists": "Profile tile",
        "deaths": "Profile and aircraft tiles",
        "accuracy": "Gun accuracy tiles (profile air / ground, aircraft, sortie)",
        "planes-lost": "Profile and aircraft tiles",
        "bailouts": "Profile tile",
        "captures": "Profile tile",
        "taxi-accidents": "Profile hall of shame (humorous): crashed before taking off",
        "strafed": "Profile hall of shame (humorous): destroyed while parked",
        "friendly-fire": "Profile hall of shame: friendly-fire kills (friendly aircraft and ground objects destroyed)",
    }
    for name, text in stat_uses.items():
        add(f"stat/{name}.svg", f"{text} (`stat_tile ... icon=`)", ICON, "P2", True)
    for name in ("elo-prop", "elo-jet", "interception", "ground-hour", "play-time"):
        add(f"stat/{name}.svg", "Leaderboard switcher button (chess pieces for the Elo boards)", ICON, "P2", True)

    # achievement medals (FR-WEB-26): one icon per achievement, drawn inside a round badge that CSS tints per tier
    for name, text in (
        ("life-kills", "Charmed Life: air kills in one life"),
        ("sortie-kills", "Ace of the Sortie: air kills in one sortie"),
        ("career-kills", "Sky Hunter: air kills in total"),
        ("strike-hunter", "Bomber Hunter: bombers, attackers and transports shot down"),
        ("tank-buster", "Tank Buster: tanks destroyed"),
        ("ground-sortie", "Target-Rich: ground targets in one sortie"),
        ("survivor", "Ironman: sorties survived in a row"),
        ("damaged-landing", "Limping Home: badly damaged aircraft landed after a kill"),
        ("regular", "Regular: weeks played in a row"),
        ("frequent-flyer", "Frequent Flyer: sorties flown"),
        ("flight-hours", "Hours Aloft: flight time in total"),
        ("type-veteran", "Type Veteran: flight time in one aircraft type"),
        ("elo-peak", "Top Rated: the highest Elo reached"),
        ("ground-score", "Ground Pounder: the ground score in total"),
        ("ram", "Contact Sport: enemy aircraft rammed"),
        ("first-blood", "First Blood: first air kill of a mission"),
        ("multi-kill", "Hot Streak: several air kills within two minutes"),
        ("types-flown", "Type Collector: different aircraft types flown"),
        ("types-with-kills", "Versatile Hunter: different aircraft types with an air kill"),
        ("landing-streak", "Soft Touch: landings in a row"),
        ("ace-in-a-day", "Ace in a Day: air kills in one day"),
        ("tours-in-a-row", "Old Hand: tours flown in a row (all time only)"),
        ("shame-taxi", "Ramp Rash (hall of shame): taxi accidents"),
        ("shame-friendly", "Wrong Team (hall of shame): friendly-fire kills"),
        ("shame-strafed", "Sitting Duck (hall of shame): destroyed on the ground by an attacker"),
        ("shame-crashed", "Hard Landing (hall of shame): crashed after take-off"),
    ):
        add(
            f"medal/{name}.svg",
            f"Medal row (profile, achievement pages, sortie page): {text}; CSS tints it by tier",
            ICON,
            "P2",
            True,
            dynamic=True,
        )

    # navigation link icons: the admin picks one per custom link by key (web.site_forms), so the name is computed
    for name in NAV_ICONS:
        add(f"nav/{name}.svg", "Custom navigation links in the header (`NavLink.icon`)", ICON, "P3", True, dynamic=True)

    # language flags (web.templatetags.il2ks.LANGUAGE_FLAGS): decorative `<img alt="">` in the footer language menu
    for name, text in (
        ("us", "English (American English)"),
        ("ru", "Russian"),
        ("de", "German"),
        ("es", "Spanish"),
        ("fr", "French"),
        ("br", "Brazilian Portuguese"),
    ):
        add(f"flag/{name}.svg", f"Footer language menu: {text}", "SVG, 4:3 flag, viewBox 640 x 480", "P2", True)

    # textures and illustrations
    add(
        "pattern/camo.svg",
        "Header band and home hero background (CSS `--il2-camo`), tiled, very low contrast",
        "SVG 640 x 200 tile",
        "P2",
        True,
    )
    add("illustration/404.svg", "Page-not-found page", "SVG, viewBox 120 x 80, uses currentColor", "P2", True)
    add("illustration/500.svg", "Server-error page", "SVG, viewBox 120 x 80, uses currentColor", "P3", True)
    add(
        "illustration/empty.svg",
        "Empty table rows (`empty_row` component)",
        "SVG, viewBox 120 x 80, uses currentColor",
        "P2",
        True,
    )
    add(
        "illustration/loading.svg",
        "Loading indicator for live search and table updates (not wired yet)",
        "SVG, small, animated or static",
        "P3",
        False,
    )

    assert len({a.path for a in assets}) == len(assets), "duplicate manifest path"
    return assets


# --- tabler sources (README.md is the record; the manifest does not repeat it) -----------------------------------


def tabler_sources(readme: Path = README) -> dict[str, str]:
    """`event/spawn.svg` -> `login`, from the README's Tabler table."""
    rows = re.findall(
        r"^\| `([a-z0-9/_-]+\.svg)` \| `([a-z0-9-]+)` \|$", readme.read_text(encoding="utf-8"), re.MULTILINE
    )
    return dict(rows)


def source_of(path: str, tabler: dict[str, str]) -> str:
    if path in tabler:
        return f"Tabler `{tabler[path]}`"
    if path.startswith("flag/"):
        return "flag-icons (MIT)"
    if path.startswith(OURS):
        return "own drawing"
    return "none yet"


# --- what the code references and what is on disk ----------------------------------------------------------------

_QUOTED = re.compile(
    r"""["']((?:aircraft|brand|coalition|event|ground|outcome|role|stat|flag|medal|pattern|illustration)/[a-z0-9][a-z0-9_/-]*)["']"""
)
_PATHED = re.compile(
    r"img/((?:aircraft|brand|coalition|event|ground|outcome|role|stat|flag|medal|pattern|illustration)/[a-z0-9][a-z0-9_/-]*\.(?:svg|png|webp))"
)


def referenced() -> dict[str, list[str]]:
    """Image paths (with extension) named literally in templates, CSS, JS and Python, with the files naming them.

    Names built at run time (insignia choice, an aircraft's own icon) are not found here: those manifest entries are
    marked `dynamic`."""
    files: Iterable[Path] = [
        *(WEB_DIR / "templates").rglob("*.html"),
        *WEB_DIR.rglob("*.py"),
        *(WEB_DIR / "static" / "il2ks").glob("*.css"),
        *(WEB_DIR / "static" / "il2ks").glob("*.js"),
    ]
    found: dict[str, list[str]] = {}
    for path in files:
        text = path.read_text(encoding="utf-8")
        names = [f"{m.group(1)}.svg" for m in _QUOTED.finditer(text)] + [m.group(1) for m in _PATHED.finditer(text)]
        for name in names:
            where = found.setdefault(name, [])
            if path.name not in where:
                where.append(path.name)
    return found


def on_disk() -> set[str]:
    return {p.relative_to(IMG_DIR).as_posix() for p in IMG_DIR.rglob("*") if p.is_file() and p.name != "README.md"}


def status_of(asset: Asset, disk: set[str], refs: dict[str, list[str]]) -> Status:
    used = asset.dynamic or asset.path in refs
    if asset.path in disk:
        return "shipped" if used else "unused"
    return "missing" if asset.path in refs else "planned"


@dataclass(frozen=True)
class Drift:
    """Differences between the manifest, the code and the disk. All lists empty = the brief is complete."""

    missing: list[str]  # referenced by code (or release-required and wired) but no file
    unlisted_files: list[str]  # on disk, not in the manifest
    unlisted_refs: list[str]  # named in code, not in the manifest
    unused: list[
        str
    ]  # release-required and on disk, but nothing references it (optional ones may sit unused: state `unused`)
    tabler_unknown: list[str]  # on disk, neither in the README's Tabler table nor an own drawing
    tabler_stale: list[str]  # in the README's Tabler table, no file

    def ok(self) -> bool:
        return not any(
            (self.missing, self.unlisted_files, self.unlisted_refs, self.unused, self.tabler_unknown, self.tabler_stale)
        )


def find_drift(manifest: list[Asset] | None = None) -> Drift:
    manifest = manifest or build_manifest()
    disk, refs, tabler = on_disk(), referenced(), tabler_sources()
    listed = {a.path for a in manifest}
    dynamic = {a.path for a in manifest if a.dynamic}
    return Drift(
        missing=sorted(p for p in refs if p not in disk and p not in dynamic)
        + sorted(a.path for a in manifest if a.release and a.path not in disk),
        unlisted_files=sorted(disk - listed),
        unlisted_refs=sorted(set(refs) - listed),
        unused=sorted(
            a.path for a in manifest if a.release and a.path in disk and not a.dynamic and a.path not in refs
        ),
        tabler_unknown=sorted(p for p in disk if p not in tabler and not p.startswith(OURS)),
        tabler_stale=sorted(p for p in tabler if p not in disk),
    )


# --- the brief -----------------------------------------------------------------------------------------------------


def render(manifest: list[Asset] | None = None) -> str:
    """The generated section of doc 15 (between START and END)."""
    manifest = manifest or build_manifest()
    disk, refs, tabler = on_disk(), referenced(), tabler_sources()
    shipped = sum(a.path in disk for a in manifest)
    lines = [
        START,
        "",
        "## Complete file inventory",
        "",
        "Generated from the code by `uv run il2ks dev assets --write`; a unit test fails when it drifts from the "
        "templates, "
        "the Python icon maps, the CSS or the files in `static/il2ks/img/`. Paths are relative to "
        "`src/il2ks/web/static/il2ks/img/`. **Release**: *yes* = the page needs the file (a placeholder is enough), "
        "*no* = optional or later. **State**: *shipped* = a placeholder file exists, *unused* = shipped but no page "
        "uses it yet, *planned* = not drawn and not "
        "(fully) wired yet; the site works without it. The uploaded server logo is not a static file: it is "
        "re-encoded to PNG (at most 256 px high) and served from `/media/branding/`.",
        "",
        f"Total: {len(manifest)} files in {len(GROUPS)} groups; {shipped} shipped as placeholders "
        f"({sum(status_of(a, disk, refs) == 'unused' for a in manifest)} of them not used by any page yet), "
        f"{len(manifest) - shipped} planned.",
        "",
    ]
    for group in GROUPS:
        rows = [a for a in manifest if a.group == group]
        count = sum(a.path in disk for a in rows)
        lines += [
            f"### {GROUP_TITLES[group]}: {len(rows)} files ({count} shipped)",
            "",
            "| File | Used in | Size / format | Placeholder source | Release | Prio | State |",
            "|---|---|---|---|---|---|---|",
        ]
        for a in rows:
            state = status_of(a, disk, refs)
            lines.append(
                f"| `{a.path}` | {a.used_in} | {a.size} | {source_of(a.path, tabler)} | "
                f"{'yes' if a.release else 'no'} | {a.priority} | {state} |"
            )
        lines.append("")
    lines.append(END)
    return "\n".join(lines)


def brief_path(root: Path | None = None) -> Path:
    base = root or Path(__file__).resolve().parents[3]
    return base / "design_doc" / BRIEF_NAME


def brief_section(text: str) -> str | None:
    start, end = text.find(START), text.find(END)
    return text[start : end + len(END)] if start != -1 and end > start else None


def write_brief(path: Path) -> bool:
    """Replace the generated section of the brief (appended if absent). True when the file changed."""
    text = path.read_text(encoding="utf-8")
    section = render()
    current = brief_section(text)
    new = text.replace(current, section) if current else text.rstrip("\n") + "\n\n" + section + "\n"
    if new == text:
        return False
    path.write_text(new, encoding="utf-8", newline="\n")
    return True


def summary(manifest: list[Asset] | None = None) -> str:
    manifest = manifest or build_manifest()
    disk = on_disk()
    out = ["group          files  shipped  planned  release-required"]
    for group in GROUPS:
        rows = [a for a in manifest if a.group == group]
        have = sum(a.path in disk for a in rows)
        out.append(f"{group:<14}{len(rows):>6}{have:>9}{len(rows) - have:>9}{sum(a.release for a in rows):>18}")
    out.append(f"{'total':<14}{len(manifest):>6}{len(disk):>9}{len(manifest) - len(disk):>9}")
    drift = find_drift(manifest)
    for label, items in (
        ("referenced or release-required but missing", drift.missing),
        ("on disk but not in the manifest", drift.unlisted_files),
        ("referenced but not in the manifest", drift.unlisted_refs),
        ("shipped but referenced nowhere", drift.unused),
        ("on disk, not in the README (Tabler table or own drawings)", drift.tabler_unknown),
        ("in the README's Tabler table but no file", drift.tabler_stale),
    ):
        if items:
            out.append(f"{label}: {', '.join(items)}")
    return "\n".join(out)


def run(*, check: bool, write: bool) -> int:
    """`il2ks dev assets`: print the summary; `--check` exits 1 on drift; `--write` rewrites the brief's inventory."""
    path = brief_path()
    if write and write_brief(path):
        print(f"rewrote the inventory in {path}")
    print(summary())
    if not check:
        return 0
    drift = find_drift()
    in_brief = brief_section(path.read_text(encoding="utf-8")) == render()
    if not in_brief:
        print("design_doc/15_visual_assets.md is out of date: run `uv run il2ks dev assets --write`", flush=True)
    return 0 if drift.ok() and in_brief else 1
