"""The bundled HTTPS proxy, Caddy (TD-23): finding the binary and writing its Caddyfile from the config.

The Caddyfile is generated, never edited by hand: `il2ks run` rewrites `<data dir>/caddy/Caddyfile` at every start.
Caddy keeps its certificates and ACME account under `<data dir>/caddy/data` (see `caddy_environment`), so several
installs on one machine (FR-OPS-5) don't share state, and a backup of the data dir carries the certificates.

Certificate plans, in the order TD-23 gives them:
- `public`: a domain name, certificate from a public CA (Let's Encrypt) through ACME. Caddy does all of it.
- `public-ip`: the domain setting is an IP address. Let's Encrypt has issued IP-address certificates since early 2026
  (valid about 6 days, renewed automatically); Caddy 2.10 and later can order them when asked for the ACME profile
  `shortlived`. IPv4 works in 2.10; IPv6 needed fixes that landed in 2026 releases. The address must be public.
- `internal`: Caddy's own CA (`cert = "internal"`): browsers warn. For testing only.
- `internal-no-domain`: no domain set at all. Same, for any name or address the visitor uses. Testing only.
"""

import ipaddress
import os
import shutil
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from il2ks.config import Config

type CertPlan = Literal["public", "public-ip", "internal", "internal-no-domain"]

CADDYFILE_NAME = "Caddyfile"
ACCESS_LOG_NAME = "caddy-access.log"
CADDY_ACCESS_LOG_MIB = 10


def caddy_dir(cfg: Config) -> Path:
    return cfg.data_dir / "caddy"


def caddyfile_path(cfg: Config) -> Path:
    return caddy_dir(cfg) / CADDYFILE_NAME


def caddy_binary_name() -> str:
    return "caddy.exe" if os.name == "nt" else "caddy"


def find_caddy(cfg: Config, *, path_lookup: str | None = None) -> Path | None:
    """The Caddy binary: `[https] caddy_path`, then the PATH, then `<data dir>/bin/caddy(.exe)`.

    A configured `caddy_path` that doesn't exist is not silently replaced by another Caddy: None, so the admin sees
    the mistake. `path_lookup` replaces `shutil.which` result (for tests)."""
    configured = cfg.https.caddy_path
    if configured is not None:
        return configured if configured.is_file() else None
    found = path_lookup if path_lookup is not None else shutil.which("caddy")
    if found:
        return Path(found)
    bundled = cfg.data_dir / "bin" / caddy_binary_name()
    return bundled if bundled.is_file() else None


def is_ip_address(text: str) -> bool:
    try:
        ipaddress.ip_address(text.strip("[]"))
    except ValueError:
        return False
    return True


def cert_plan(cfg: Config) -> CertPlan:
    https = cfg.https
    if not https.domain:
        return "internal-no-domain"
    if https.cert == "internal":
        return "internal"
    return "public-ip" if is_ip_address(https.domain) else "public"


def cert_plan_warning(plan: CertPlan) -> str:
    """The loud message for plans that browsers distrust; "" for the real ones."""
    if plan == "internal-no-domain":
        return (
            "No [https] domain is set: Caddy uses its own self-signed certificate. Browsers will warn "
            "'not secure'. This is for TESTING ONLY. Set [https] domain to a name (or public IP address) "
            "for a real certificate."
        )
    if plan == "internal":
        return (
            "[https] cert = 'internal': Caddy uses its own self-signed certificate. Browsers will warn "
            "'not secure'. This is for TESTING ONLY."
        )
    return ""


def upstream(cfg: Config) -> str:
    """Where Caddy forwards to: the web server's address (a wildcard bind address means "this machine")."""
    host = cfg.web.host
    if host in {"0.0.0.0", "", "::", "[::]"}:
        host = "127.0.0.1"
    if ":" in host and not host.startswith("["):
        host = f"[{host}]"
    return f"{host}:{cfg.web.port}"


def _quote(path: Path) -> str:
    """A path as a Caddyfile word: forward slashes (also on Windows), double-quoted."""
    return '"' + path.as_posix().replace('"', '\\"') + '"'


def _site_address(domain: str) -> str:
    domain = domain.strip("[]")
    return f"[{domain}]" if ":" in domain else domain


def render_caddyfile(cfg: Config) -> str:
    """The complete Caddyfile for this config."""
    https = cfg.https
    plan = cert_plan(cfg)
    internal = plan in {"internal", "internal-no-domain"}
    keep_hours = cfg.log_keep_days * 24
    access_log = _quote(cfg.log_dir / ACCESS_LOG_NAME)

    lines = [
        "# Generated by il2ks from il2ks.toml every time `il2ks run` starts. Do not edit: changes are overwritten.",
        "# Change the settings in il2ks.toml ([https], [web]) instead.",
        "{",
        "\tadmin off",
        f"\thttp_port {https.http_port}",
        f"\thttps_port {https.https_port}",
    ]
    if https.email:
        lines.append(f"\temail {https.email}")
    if internal:
        lines.append("\tskip_install_trust")  # never touch the machine's trust store; this is for testing
    lines += ["\tlog {", "\t\toutput stderr", "\t\tformat console", "\t}", "}", ""]

    body = [
        "\tencode zstd gzip",
        "\tlog {",
        f"\t\toutput file {access_log} {{",
        f"\t\t\troll_size {CADDY_ACCESS_LOG_MIB}MiB",
        f"\t\t\troll_keep_for {keep_hours}h",
        "\t\t}",
        "\t}",
        f"\treverse_proxy {upstream(cfg)}",
    ]
    if plan == "internal-no-domain":
        # No name to certify: serve whatever name or address the visitor used, certificates from the local CA only.
        lines += [f":{https.https_port} {{", "\ttls internal {", "\t\ton_demand", "\t}", *body, "}", ""]
        lines += [
            f"http://:{https.http_port} {{",
            f"\tredir https://{{host}}{_port_suffix(https.https_port)}{{uri}} permanent",
            "}",
        ]
        return "\n".join(lines) + "\n"

    tls: list[str] = []
    if plan == "internal":
        tls = ["\ttls internal"]
    elif plan == "public-ip":
        tls = ["\ttls {", "\t\tissuer acme {", "\t\t\tprofile shortlived", "\t\t}", "\t}"]
    lines += [f"{_site_address(https.domain)} {{", *tls, *body, "}"]
    if https.https_port != 443:
        # Caddy's automatic redirect leaves the port out of the address; with a non-standard port that would be wrong.
        lines += [
            "",
            f"http://{_site_address(https.domain)}:{https.http_port} {{",
            f"\tredir https://{{host}}{_port_suffix(https.https_port)}{{uri}} permanent",
            "}",
        ]
    return "\n".join(lines) + "\n"


def _port_suffix(https_port: int) -> str:
    return "" if https_port == 443 else f":{https_port}"


def caddy_environment(cfg: Config, base: Mapping[str, str] | None = None) -> dict[str, str]:
    """Environment for the Caddy process: its certificate storage and autosaved config live in our data dir."""
    env = dict(os.environ if base is None else base)
    root = caddy_dir(cfg)
    env["XDG_DATA_HOME"] = str(root / "data")
    env["XDG_CONFIG_HOME"] = str(root / "config")
    return env


def caddy_command(binary: Path, cfg: Config) -> list[str]:
    return [str(binary), "run", "--config", str(caddyfile_path(cfg)), "--adapter", "caddyfile"]


@dataclass(frozen=True, slots=True)
class CaddySetup:
    binary: Path
    command: list[str]
    env: dict[str, str]
    plan: CertPlan


def write_caddyfile(cfg: Config) -> Path:
    """Write `<data dir>/caddy/Caddyfile` (and the folders Caddy needs); returns its path."""
    path = caddyfile_path(cfg)
    path.parent.mkdir(parents=True, exist_ok=True)
    cfg.log_dir.mkdir(parents=True, exist_ok=True)
    path.write_text(render_caddyfile(cfg), encoding="utf-8", newline="\n")
    return path


def prepare_caddy(cfg: Config, binary: Path) -> CaddySetup:
    """Write the Caddyfile and describe how to start Caddy."""
    write_caddyfile(cfg)
    return CaddySetup(
        binary=binary,
        command=caddy_command(binary, cfg),
        env=caddy_environment(cfg),
        plan=cert_plan(cfg),
    )
