"""`il2ks web`, `il2ks run`, `il2ks caddyfile`: wiring, refusals and the order of the steps, with everything that starts
a server or a process replaced by a recorder."""

import argparse
import os
import signal
import subprocess
import sys
import textwrap
import threading
import time
from collections.abc import Callable, Sequence
from pathlib import Path

import pytest
from pytest_django.fixtures import Settings

from il2ks import cli
from il2ks.cli import EXIT_FAILED, EXIT_LOCKED, EXIT_OK, EXIT_USAGE, PLANNED, main
from il2ks.config import Config, ConfigError, load_config
from il2ks.ingest.lock import LockBusyError, LockHolder
from il2ks.serving import commands, procutil, webserver
from il2ks.serving.secret import DEV_SECRET_KEY, SECRET_KEY_FILE
from il2ks.serving.supervisor import ChildSpec
from tests.unit.test_supervisor import FakeChild

ENV_KEYS = ("IL2KS_DATA_DIR", "IL2KS_CONFIG", "IL2KS_DEBUG", "IL2KS_LOGS_DIR")


@pytest.fixture
def env(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Env vars the commands export are undone after the test; logging setup is not touched."""
    for key in ENV_KEYS:
        monkeypatch.setenv(key, "")  # registers the undo
        monkeypatch.delenv(key)
    monkeypatch.setenv("IL2KS_DATA_DIR", str(tmp_path / "data"))
    monkeypatch.chdir(tmp_path)

    def no_logging(process: str, cfg: Config) -> None:
        return None

    monkeypatch.setattr(commands, "start_logging", no_logging)
    return tmp_path


class Calls:
    """Records what the web command did, in order."""

    def __init__(self) -> None:
        self.events: list[str] = []
        self.served: list[tuple[str, str | int, str | int]] = []

    def migrate(self, cfg: Config, name: str, wait: float | None) -> None:
        self.events.append(f"migrate:{name}")


@pytest.fixture
def calls(monkeypatch: pytest.MonkeyPatch) -> Calls:
    recorded = Calls()

    def collectstatic(*args: object, **kwargs: object) -> None:
        recorded.events.append(f"call_command:{args[0]}")

    def granian(cfg: Config, host: str, port: int) -> None:
        recorded.events.append("serve_granian")
        recorded.served.append(("granian", host, port))

    def dev(host: str, port: int, *, reload: bool) -> None:
        recorded.events.append("serve_dev")
        recorded.served.append(("dev", host, port))

    monkeypatch.setattr("django.core.management.call_command", collectstatic)
    monkeypatch.setattr(webserver, "serve_granian", granian)
    monkeypatch.setattr(webserver, "serve_dev", dev)
    return recorded


def hooks_for(calls: Calls) -> commands.Hooks:
    return commands.Hooks(django_setup=lambda: None, migrate=calls.migrate)


def parse(argv: list[str]) -> argparse.Namespace:
    return cli._build_parser().parse_args(argv)  # pyright: ignore[reportPrivateUsage]


# --- wiring ---------------------------------------------------------------------------------------------------------


def test_web_and_run_are_no_longer_stubs() -> None:
    assert "web" not in PLANNED
    assert "run" not in PLANNED


@pytest.mark.parametrize("argv", [["web"], ["run"], ["caddyfile"], ["service"], ["custom"], ["service", "systemd"]])
def test_help_exists(argv: list[str], capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as info:
        main([*argv, "--help"])
    assert info.value.code == 0
    assert "usage: il2ks" in capsys.readouterr().out


def test_version(capsys: pytest.CaptureFixture[str]) -> None:
    with pytest.raises(SystemExit) as info:
        main(["--version"])
    assert info.value.code == 0
    from il2ks import __version__

    assert capsys.readouterr().out.strip() == f"il2ks {__version__}"


def test_caddyfile_prints_what_run_would_write(env: Path, capsys: pytest.CaptureFixture[str]) -> None:
    assert main(["caddyfile"]) == EXIT_OK
    out = capsys.readouterr().out
    assert out.startswith("# Generated by il2ks")
    assert "reverse_proxy 127.0.0.1:8000" in out
    assert not (env / "data" / "caddy").exists()  # printing writes nothing


def test_a_bad_config_is_a_usage_error(
    env: Path, monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
    monkeypatch.setenv("IL2KS_WEB_PORT", "nope")
    assert main(["caddyfile"]) == EXIT_USAGE
    assert "configuration error: web.port" in capsys.readouterr().err
    with pytest.raises(ConfigError):
        load_config(None, {"IL2KS_WEB_PORT": "nope"}, create_server_uid=False)


# --- web ------------------------------------------------------------------------------------------------------------


def test_web_refuses_the_development_key_outside_dev_mode(
    env: Path, calls: Calls, settings: Settings, capsys: pytest.CaptureFixture[str]
) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = DEV_SECRET_KEY
    assert commands.dispatch(parse(["web"]), hooks_for(calls)) == EXIT_USAGE
    assert "refusing to start with the built-in development secret key" in capsys.readouterr().err
    assert calls.events == []  # nothing migrated, collected or served


def test_web_creates_the_secret_key_file_before_django_starts(env: Path, calls: Calls, settings: Settings) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"
    assert commands.dispatch(parse(["web"]), hooks_for(calls)) == EXIT_OK
    assert (env / "data" / SECRET_KEY_FILE).read_text(encoding="utf-8").strip()


def test_web_migrates_then_collects_static_then_serves(env: Path, calls: Calls, settings: Settings) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"
    assert commands.dispatch(parse(["web"]), hooks_for(calls)) == EXIT_OK
    assert calls.events == ["migrate:web", "call_command:collectstatic", "serve_granian"]
    assert calls.served == [("granian", "127.0.0.1", 8000)]
    assert (env / "data" / "custom" / "templates").is_dir()  # custom/ folders exist for the admin
    assert (env / "data" / "custom" / "static").is_dir()


def test_web_host_and_port_options_override_the_config(env: Path, calls: Calls, settings: Settings) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"
    commands.dispatch(parse(["web", "--host", "0.0.0.0", "--port", "9100"]), hooks_for(calls))
    assert calls.served == [("granian", "0.0.0.0", 9100)]


def test_web_dev_is_plain_http_debug_without_collectstatic_or_secret_file(
    env: Path, calls: Calls, settings: Settings
) -> None:
    settings.DEBUG = True
    settings.SECRET_KEY = DEV_SECRET_KEY
    assert commands.dispatch(parse(["web", "--dev", "--port", "8123"]), hooks_for(calls)) == EXIT_OK
    assert calls.events == ["migrate:web", "serve_dev"]
    assert calls.served == [("dev", "127.0.0.1", 8123)]
    assert os.environ["IL2KS_DEBUG"] == "1"  # so settings.py (and children) run in debug mode
    assert not (env / "data" / SECRET_KEY_FILE).exists()


def test_web_migrate_only_applies_migrations_and_exits(env: Path, calls: Calls, settings: Settings) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"
    assert commands.dispatch(parse(["web", "--migrate-only"]), hooks_for(calls)) == EXIT_OK
    assert calls.events == ["migrate:web"]


def test_web_reports_a_busy_writer_lock(env: Path, settings: Settings, capsys: pytest.CaptureFixture[str]) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"

    def busy(cfg: Config, name: str, wait: float | None) -> None:
        raise LockBusyError(Path("writer.lock"), None)

    hooks = commands.Hooks(django_setup=lambda: None, migrate=busy)
    assert commands.dispatch(parse(["web"]), hooks) == EXIT_LOCKED
    assert "another il2ks writer is running" in capsys.readouterr().err


def test_web_ctrl_c_is_a_clean_stop(
    env: Path, calls: Calls, settings: Settings, monkeypatch: pytest.MonkeyPatch
) -> None:
    settings.DEBUG = False
    settings.SECRET_KEY = "a-real-key-for-this-test"

    def interrupted(cfg: Config, host: str, port: int) -> None:
        raise KeyboardInterrupt

    monkeypatch.setattr(webserver, "serve_granian", interrupted)
    assert commands.dispatch(parse(["web"]), hooks_for(calls)) == EXIT_OK


def test_the_config_is_exported_for_settings_and_children(env: Path, calls: Calls, settings: Settings) -> None:
    settings.DEBUG = True
    config_file = env / "il2ks.toml"
    config_file.write_text("[web]\nport = 8765\n", encoding="utf-8")
    commands.dispatch(parse(["--config", str(config_file), "web", "--dev"]), hooks_for(calls))
    assert os.environ["IL2KS_CONFIG"] == str(config_file)
    assert os.environ["IL2KS_DATA_DIR"] == str(env / "data")
    assert calls.served == [("dev", "127.0.0.1", 8765)]


# --- run ------------------------------------------------------------------------------------------------------------


def make_cfg(tmp_path: Path, toml: str = "") -> Config:
    file = tmp_path / "il2ks.toml"
    file.write_text(toml, encoding="utf-8")
    return load_config(file, {"IL2KS_DATA_DIR": str(tmp_path / "data")}, create_server_uid=False)


def fake_caddy(tmp_path: Path) -> Path:
    binary = tmp_path / "caddy.exe"
    binary.write_bytes(b"")
    return binary


def test_child_specs_are_web_watch_and_caddy(tmp_path: Path) -> None:
    logs = tmp_path / "logs"
    cfg = make_cfg(tmp_path, f'[logs]\ndir = "{logs.as_posix()}"\n[https]\ndomain = "stats.example.com"')
    specs = commands.build_child_specs(cfg, caddy_binary=fake_caddy(tmp_path), env={"PATH": "p"})
    assert [s.name for s in specs] == ["web", "watch", "caddy"]
    web, watch, caddy = specs
    assert list(web.command)[1:3] == ["-m", "il2ks"]
    assert list(web.command)[-1] == "web"
    assert "--config" in web.command
    assert str(cfg.source) in web.command
    assert list(watch.command)[-1] == "watch"
    assert caddy.command[1] == "run"
    assert caddy.forward_output is True
    assert web.env is not None
    assert web.env["PYTHONUNBUFFERED"] == "1"
    assert web.env["PATH"] == "p"
    assert caddy.env is not None
    assert "XDG_DATA_HOME" in caddy.env
    assert (tmp_path / "data" / "caddy" / "Caddyfile").is_file()


def test_external_mode_has_no_caddy(tmp_path: Path) -> None:
    cfg = make_cfg(tmp_path, '[logs]\ndir = "x"\n[https]\nmode = "external"')
    assert [s.name for s in commands.build_child_specs(cfg, caddy_binary=None, env={})] == ["web", "watch"]


def test_debug_mode_has_no_caddy(tmp_path: Path) -> None:
    cfg = make_cfg(tmp_path, 'debug = true\n[logs]\ndir = "x"')
    assert [s.name for s in commands.build_child_specs(cfg, caddy_binary=None, env={})] == ["web", "watch"]


def test_without_a_log_folder_there_is_no_watch(tmp_path: Path, caplog: pytest.LogCaptureFixture) -> None:
    cfg = make_cfg(tmp_path, '[https]\nmode = "external"')
    assert [s.name for s in commands.build_child_specs(cfg, caddy_binary=None, env={})] == ["web"]
    assert "nothing is ingested" in caplog.text


def test_missing_caddy_says_how_to_get_it(tmp_path: Path) -> None:
    cfg = make_cfg(tmp_path, '[logs]\ndir = "x"')
    with pytest.raises(commands.StackError) as info:
        commands.build_child_specs(cfg, caddy_binary=None, env={})
    message = str(info.value)
    assert "winget install CaddyServer.Caddy" in message
    assert 'mode = "external"' in message
    assert str(tmp_path / "data" / "bin") in message


def test_a_test_certificate_warning_is_loud(tmp_path: Path, capsys: pytest.CaptureFixture[str]) -> None:
    cfg = make_cfg(tmp_path, '[logs]\ndir = "x"')  # no domain
    commands.build_child_specs(cfg, caddy_binary=fake_caddy(tmp_path), env={})
    assert "TESTING ONLY" in capsys.readouterr().err


class RunWorld:
    def __init__(self) -> None:
        self.spawned: list[FakeChild] = []
        self.prepared: list[list[str]] = []
        self.prepare_code = 0
        self.signals_installed = 0
        self.finished = 0
        self.contained: list[int] = []
        self.stop = threading.Event()

    def spawn(self, spec: ChildSpec) -> FakeChild:
        child = FakeChild(spec)
        self.spawned.append(child)
        return child

    def runner(self, args: Sequence[str]) -> int:
        self.prepared.append(list(args))
        return self.prepare_code

    def install_signals(self, stop: threading.Event) -> Callable[[], None]:
        self.signals_installed += 1
        self.stop = stop

        def finished() -> None:
            self.finished += 1

        return finished

    def sleep(self, seconds: float) -> None:
        self.stop.set()  # "Ctrl+C" right after the children started

    def contain(self) -> bool:
        self.contained.append(len(self.spawned))  # how many children existed when it was called
        return True

    def hooks(self, calls: Calls) -> commands.Hooks:
        return commands.Hooks(
            django_setup=lambda: None,
            migrate=calls.migrate,
            spawn=self.spawn,
            runner=self.runner,
            install_signals=self.install_signals,
            sleep=self.sleep,
            contain_children=self.contain,
        )


def test_run_prepares_the_database_starts_everything_and_stops_it_cleanly(env: Path, calls: Calls) -> None:
    (env / "il2ks.toml").write_text(
        f'[logs]\ndir = "{env.as_posix()}"\n[https]\ncaddy_path = "{fake_caddy(env).as_posix()}"', encoding="utf-8"
    )
    world = RunWorld()
    assert commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls)) == EXIT_OK

    assert len(world.prepared) == 1
    assert world.prepared[0][-2:] == ["web", "--migrate-only"]
    assert [c.spec.name for c in world.spawned] == ["web", "watch", "caddy"]
    assert all(c.stop_called for c in world.spawned)  # stopped, not abandoned
    assert world.finished == 1
    assert (env / "data" / SECRET_KEY_FILE).exists()  # created before the children, so they don't race
    assert procutil.read_run_state(env / "data") is None  # run.json is removed on exit
    assert world.contained == [0]  # the children are tied to us before the first one starts
    assert procutil.running_stack(env / "data") is None  # and the run lock is released


def test_run_holds_the_run_lock_while_it_runs(env: Path, calls: Calls) -> None:
    (env / "il2ks.toml").write_text('[https]\nmode = "external"', encoding="utf-8")
    world = RunWorld()
    seen: list[object] = []
    original_sleep = world.sleep

    def sleep(seconds: float) -> None:
        seen.append(procutil.running_stack(env / "data"))
        original_sleep(seconds)

    world.sleep = sleep
    commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls))
    assert seen
    holder = seen[0]
    assert isinstance(holder, LockHolder)
    assert holder.pid == os.getpid()
    assert holder.command == "run"


def test_run_writes_run_json_while_running(env: Path, calls: Calls, monkeypatch: pytest.MonkeyPatch) -> None:
    (env / "il2ks.toml").write_text('[https]\nmode = "external"', encoding="utf-8")
    world = RunWorld()
    seen: list[procutil.RunState | None] = []
    original = procutil.write_run_state

    def spy(data_dir: Path, children: dict[str, int]) -> None:
        original(data_dir, children)
        seen.append(procutil.read_run_state(data_dir))

    monkeypatch.setattr(procutil, "write_run_state", spy)
    commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls))
    assert seen
    assert seen[-1] is not None
    assert seen[-1].pid == os.getpid()
    assert list(seen[-1].children) == ["web"]


def test_run_does_not_start_if_the_database_cannot_be_prepared(
    env: Path, calls: Calls, capsys: pytest.CaptureFixture[str]
) -> None:
    (env / "il2ks.toml").write_text('[https]\nmode = "external"', encoding="utf-8")
    world = RunWorld()
    world.prepare_code = 1
    assert commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls)) == EXIT_FAILED
    assert world.spawned == []
    assert "not starting" in capsys.readouterr().err


def test_run_refuses_a_second_copy_for_the_same_data_dir(
    env: Path, calls: Calls, capsys: pytest.CaptureFixture[str], monkeypatch: pytest.MonkeyPatch
) -> None:
    (env / "il2ks.toml").write_text('[https]\nmode = "external"', encoding="utf-8")
    (env / "data").mkdir()
    monkeypatch.setattr(commands, "RUN_LOCK_WAIT_S", 0.0)
    world = RunWorld()
    with procutil.run_lock(env / "data"):  # another `run` holds the lock
        procutil.write_run_state(env / "data", {"web": 1})
        assert commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls)) == EXIT_LOCKED
        assert procutil.read_run_state(env / "data") is not None  # not removed by the refused copy
    assert "already running" in capsys.readouterr().err
    assert world.spawned == []
    assert world.contained == []  # a refused run doesn't tie itself to a job either


def test_run_without_caddy_exits_with_advice(env: Path, calls: Calls, capsys: pytest.CaptureFixture[str]) -> None:
    (env / "il2ks.toml").write_text(f'[https]\ncaddy_path = "{(env / "nope.exe").as_posix()}"', encoding="utf-8")
    world = RunWorld()
    assert commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls)) == EXIT_USAGE
    assert "Caddy" in capsys.readouterr().err
    assert world.spawned == []


def test_a_stale_run_json_does_not_block_a_new_run(env: Path, calls: Calls) -> None:
    """After a crash or reboot run.json names a PID that may now belong to anything, even to the new `run` itself
    (PIDs are reused). Only the OS lock counts, and the OS dropped it with the old process."""
    (env / "il2ks.toml").write_text('[https]\nmode = "external"', encoding="utf-8")
    (env / "data").mkdir()
    for pid in (os.getpid(), os.getppid(), 4):  # this process, its parent, the Windows System process: all alive
        (env / "data" / procutil.RUN_STATE_FILE).write_text(
            f'{{"pid": {pid}, "started": "2026-01-01T00:00:00+00:00", "children": {{"web": {pid}}}}}', encoding="utf-8"
        )
        (env / "data" / procutil.RUN_LOCK_FILE).write_text(  # the dead run's lock file: content, but no OS lock
            f'{{"pid": {pid}, "host": "gone", "command": "run", "since": "2026-01-01T00:00:00+00:00"}}',
            encoding="utf-8",
        )
        assert procutil.running_stack(env / "data") is None
        world = RunWorld()
        assert commands.dispatch(parse(["--config", str(env / "il2ks.toml"), "run"]), world.hooks(calls)) == EXIT_OK
        assert [c.spec.name for c in world.spawned] == ["web"]


def test_the_run_lock_is_released_when_the_holder_is_killed(tmp_path: Path) -> None:
    code = textwrap.dedent(
        f"""
        import time
        from pathlib import Path
        from il2ks.serving import procutil
        lock = procutil.run_lock(Path({str(tmp_path)!r}))
        lock.acquire()
        print("locked", flush=True)
        time.sleep(60)
        """
    )
    child = subprocess.Popen([sys.executable, "-c", code], stdout=subprocess.PIPE, text=True)
    try:
        assert child.stdout is not None
        assert child.stdout.readline().strip() == "locked"
        holder = procutil.running_stack(tmp_path)
        assert holder is not None
        assert holder.pid != os.getpid()
        with pytest.raises(LockBusyError):
            procutil.run_lock(tmp_path).acquire()
        os.kill(holder.pid, signal.SIGTERM)  # (child.pid may be the venv launcher, not the Python process)
        child.wait(timeout=30)
    finally:
        child.kill()
    assert procutil.running_stack(tmp_path) is None
    with procutil.run_lock(tmp_path):
        pass


@pytest.mark.skipif(sys.platform != "win32", reason="Windows job objects")
def test_children_die_with_run_even_when_run_is_killed_without_cleanup(tmp_path: Path) -> None:
    """`schtasks /End` / Task Manager kill `run` outright: its `finally: shutdown()` never runs. With the job object the
    OS takes web, watch and Caddy down with it (otherwise they keep the ports and the next start restart-loops)."""
    code = textwrap.dedent(
        """
        import os, subprocess, sys, time
        from il2ks.serving import procutil
        assert procutil.kill_children_when_we_die()
        child = subprocess.Popen([sys.executable, "-c", "import time; time.sleep(120)"])
        print(os.getpid(), child.pid, flush=True)
        time.sleep(120)
        """
    )
    run = subprocess.Popen([sys.executable, "-c", code], stdout=subprocess.PIPE, text=True)
    child_pid = 0
    try:
        assert run.stdout is not None
        run_pid, child_pid = (int(x) for x in run.stdout.readline().split())
        assert procutil.pid_alive(child_pid)
        os.kill(run_pid, signal.SIGTERM)  # TerminateProcess on Windows: no clean-up code runs
        deadline = time.monotonic() + 10
        while procutil.pid_alive(child_pid) and time.monotonic() < deadline:
            time.sleep(0.1)
        assert not procutil.pid_alive(child_pid)
    finally:
        run.kill()
        if child_pid and procutil.pid_alive(child_pid):  # the test failed: don't leave a sleeper behind
            subprocess.run(["taskkill", "/PID", str(child_pid), "/F"], capture_output=True, check=False)


def test_containing_the_children_is_a_noop_off_windows() -> None:
    if sys.platform == "win32":
        pytest.skip("this is the Windows implementation")
    assert procutil.kill_children_when_we_die() is False


def test_pid_alive_knows_itself_and_a_dead_pid() -> None:
    assert procutil.pid_alive(os.getpid())
    assert not procutil.pid_alive(2147483000)
    assert not procutil.pid_alive(0)


def test_manage_creates_a_missing_data_folder_so_a_first_migrate_can_create_the_database(env: Path) -> None:
    """Regression: on a fresh machine `il2ks manage migrate` crashed because SQLite cannot create its folder."""
    assert not (env / "data").exists()
    assert main(["manage", "check"]) == EXIT_OK
    assert (env / "data").is_dir()
